spockframework/spock

docs/extensions.adoc
The example used a non-existing "reason" key instead of the implicit "value" to provide the reason (as mentioned in issue #56)
=> Fixed example of "@Ignore with reason"

docs/all_in_one.adoc, docs/data_driven_testing.adoc, docs/extensions.adoc, docs/getting_started.adoc, docs/index.adoc, docs/interaction_based_testing.adoc, docs/introduction.adoc, docs/migration_guide.adoc, docs/modules.adoc, docs/release_notes.adoc, docs/spock_primer.adoc
Created all_in_one.adoc to create a single page documentation (Issue #65)
Moved all headings one level down to fix asciidoctor error: only docbook type can contain level 0 sections
=> Single page documentation Issue #65

spock-core/src/main/java/org/spockframework/runtime/BaseSpecRunner.java
Currently errors occuring inside the setup method are logged as errors of the specification. 
This way a single error can not be related to the test feature it occured on.
Additionally the feature itself is not marked as failed.
This update links each execution of the setup method to its corresponding test feature method.
=> Errors in feature setup should be logged on the feature instead of the spec

spock-specs/src/test/groovy/org/spockframework/smoke/extension/ReportLogExtensionSpec.groovy
Fix the normalize method using Matcher.quoteReplacement to avoid ambiguities between n and \n
=> Fix the normalize method in ReportLogExtensionSpec

docs/interaction_based_testing.adoc
Fixed monospace formatting in a couple of places. `Phrase` formatting
had to be changed to ``letter``.
Fixed a few typos.
=> Minor docs fixes

spock-core/src/main/java/spock/util/concurrent/PollingConditions.java, spock-specs/src/test/groovy/spock/util/concurrent/PollingConditionsSpec.groovy
Old topic:
https://groups.google.com/forum/#!topic/spockframework/FNPguVWDqWs
If executing condition closure takes longer that timeout, IAE will be produced.
```
java.lang.IllegalArgumentException: timeout value is negative
at spock.util.concurrent.PollingConditions.within(PollingConditions.java:166)
at spock.util.concurrent.PollingConditions.eventually(PollingConditions.java:134)
```
=> PolingCondition: IAE timeout value is negative

spock-specs/src/test/groovy/spock/util/concurrent/PollingConditionsSpec.groovy
The AppVeyor build is so slow that it causes the spec to fail, since the initial setup of the polling conditions eventually block takes to long. By decreasing the initialDelay, this should no longer be an issue. Furthermore, the timeouts for another test are reduced from seconds to milliseconds, as there is no reason to waste 5 seconds waiting.
=> Fix PollingConditionsSpec

build.gradle, spock-core/core.gradle, spock-core/src/main/groovy/spock/util/EmbeddedSpecCompiler.groovy, spock-core/src/main/groovy/spock/util/EmbeddedSpecRunner.groovy, spock-core/src/main/java/org/spockframework/util/inspector/AstInspector.java, spock-specs/src/test/groovy/org/spockframework/smoke/junit/JUnitFixtureMethods.groovy
By annotating parameters with @Language('Groovy') we will have IDE support
(e.g. syntax check and highlighting) for inlined languages (mostly used in tests)
=> Added @Language to String source code params

docs/data_driven_testing.adoc
`Math.max(7, 4)` should return `7`, not `4`. Fixing this example also makes it consistent with the previous `MathSpec` example it is improving upon.
=> Fix data driven testing example in documentation

spock-core/src/main/java/org/spockframework/compiler/AstUtil.java, spock-core/src/main/java/org/spockframework/compiler/WhereBlockRewriter.java, spock-core/src/main/java/org/spockframework/runtime/ParameterizedSpecRunner.java, spock-core/src/main/java/org/spockframework/util/ReflectionUtil.java, spock-specs/src/test/groovy/org/spockframework/smoke/parameterization/DataTables.groovy, spock-specs/src/test/groovy/org/spockframework/smoke/parameterization/MethodParameters.groovy, spock-specs/src/test/groovy/org/spockframework/smoke/parameterization/Parameterizations.groovy
For data driven tests it could be important for a parameter to depend
on a previously calculated value.
Until now this wasn't possible, because the whole where block was calculated,
before the test method was called (via its generated parameters).
Also, the data providers calculate the whole column,
before moving on to the next one, making the references seem unobvious.
The fix was to provide the data provider methods with the list of already
calculated columns.
And because a cell should only refer to cells in the same row,
the variable references were changed to array indexes (see the getAt part).
This commit should play well with [`partial parameter definitions`](https://github.com/spockframework/spock/pull/525).
Partially fixes: https://github.com/spockframework/spock/issues/509
=> Data table cells can reference previous ones

spock-core/src/main/java/spock/mock/MockingApi.java
Simple change to prevent "Cannot assign 'Object' to 'MyClassToMock'" warning in Idea when the following construction is used:
```
MyClassToMock mock = Stub()
```
Spock infers stub/mock type from left-hand side anyway, so it is only a better syntax to express it (like already used for example in `thrown()`). This change should not break existing code.
Maybe there was some (unknown for me reason) to use just Object and in that case please let me know.
=> Enhance Mock()/Stub() signature

spock-core/src/main/java/org/spockframework/compiler/SpecRewriter.java, spock-specs/src/test/groovy/org/spockframework/smoke/SharedFields.groovy
This pull request provides a fix for #570.
Please let me know if there is anything that this pull request is missing to get accepted, I'm happy to rework it to match your expectations.
=> Use the type of the field instead of using Object as the return type when generating getters for shared fields.

docs/extensions.adoc
Although the interaction might be obvious to some people, this makes the interaction clear.
See [this thread](https://groups.google.com/d/topic/spockframework/XEKLqOofVtc/discussion) for some background.
=> Clarify interaction of `Ignore*` annotations and `Stepwise`

spock-spring/boot-test/boot-test.gradle, spock-spring/boot-test/src/main/java/org/spockframework/boot/SimpleBootApp.java, spock-spring/boot-test/src/test/groovy/org/spockframework/boot/SimpleBootAppTestAnnotationIntegrationSpec.groovy, spock-spring/src/main/java/org/spockframework/spring/SpringExtension.java
See #581 for the issue.
Spring-Boot 1.4 will introduce a new annotation for test classes called @SpringBootTest to avoid some of the integration test boilerplate annotations.
Currently the spock-spring plugin does not recognize this annotation in order to identify this class as a Spring test class and instead relies on other annotations like @ContextHierarchy or @ContextConfiguration which do not need to be present if @SpringBootTest used.
I've introduced a check for the `@SpringBootTest` in the `SpringExtension` class similar to the other checks.
I've also added a new test for this annotation and cleaned up the `boot-test.gradle` file to include only the needed dependencies.
=> Added support for Spring-Boot 1.4 @SpringBootTest annotation

spock-report/src/main/resources/org/spockframework/report/report.html
Attachments tag was not shown in the spock report when @See annotation is used at spec level.
Fixing the same by modifying the report.html file to accommodate the same view as in the case of a feature.
=> Adding functionality to show the attachments as part of the html report for @See annotation at Spec level 

build.gradle, gradle/ide.gradle, spock-core/src/main/java/org/spockframework/mock/runtime/DefaultMethodInvoker.java, spock-core/src/main/java/org/spockframework/mock/runtime/DynamicProxyMockInterceptorAdapter.java, spock-core/src/main/java/org/spockframework/util/ReflectionUtil.java, spock-specs/specs.gradle, spock-specs/src/test.java1.8/groovy/org/spockframework/smoke/mock/PartialMockingInterfacesWithDefaultMethods.groovy, spock-specs/src/test.java1.8/java/org/spockframework/smoke/mock/IDeposit.java, spock-specs/src/test.java1.8/java/org/spockframework/smoke/mock/IQuarterlyCompoundedDeposit.java, spock-specs/src/test.java1.8/java/org/spockframework/smoke/mock/ISquare.java
Right now, the `Spy` method can be used to create a partial mock for an abstract class, as shown in the following gist: https://gist.github.com/siordache/2113afe4e381a005c4b8.
The current pull request adds the ability to create a partial mock for an interface with default methods, as shown in the following gist: https://gist.github.com/siordache/74c77618e4caceac94e9.
This pull request changes only the `DynamicProxyMockInterceptorAdapter` class. Although default methods are available only since Java 8, the code changes introduced by this pull request preserve the Java 6 compatibility.
The pull request does not contain Spock specifications for testing the new feature, because they would require Java 8. What is your opinion about requiring Java 8 for the `spock-specs` module and sticking …
=> Partial mocks for interfaces with default methods

spock-core/src/main/java/spock/lang/Specification.java
I think it would be good to make the all new things as `@Beta` to allow to get feedback from people using it in production.
=> Mark the new verifyAll method as @Beta

build.gradle
To prevent snapshot version upload from branches created by the committers
in the project repo directly.
=> Upload artifacts only from master

.github/ISSUE_TEMPLATE.md
Since I noticed duing the Hackergarten session at GR8Conf EU I noticed that most of them lacked information about the environment or how to reproduce it.
GitHub added built-in support for [issue and pull-request templates](https://help.github.com/articles/creating-an-issue-template-for-your-repository/) in earlier this year so it makes sense to use them.
=> Added an issue template to try make sure an issue contains proper info

spock-core/src/main/java/org/spockframework/compiler/DeepBlockRewriter.java, spock-specs/src/test/groovy/org/spockframework/smoke/WithBlocks.groovy
This is a fix to https://github.com/spockframework/spock/issues/588.
The root cause of the issue: 
```
def list = [1, 2]
with(list) {
contains(1)
}
```
transforms (simplified) to 
```
def list = [1, 2]
with(list) {
SpockRuntime.verifyMethodCondition(this.getThisObject(), "contains", [1])
}
```
Because the method is invoked on this but not the closure it leads to an error (Method not found).
The fix inculdes:
1. New tests for the issue case.
2. Replacing this in SpockRuntime::verifyMethodCondition with each(Closure.IDENTITY). It looks like a hack but groovy defines this in and out of closure as a reference to the same object. Any help with finding a better way to get a reference to closure itself inside this closure would be appreciated.
=> Fixed method condition invocations in closures

docs/spock_primer.adoc
With is very useful for cutting out verbosity in the object being
verified. The Javadoc for with's example in interaction based testing was
great and is the example chosen here too.
=> Document `with`

spock-spring/boot-test/boot-test.gradle, spock-spring/boot-test/src/main/java/org/spockframework/boot/jpa/Book.java, spock-spring/boot-test/src/main/java/org/spockframework/boot/jpa/BookRepository.java, spock-spring/boot-test/src/main/java/org/spockframework/boot/web/HelloWorldController.java, spock-spring/boot-test/src/test/groovy/org/spockframework/boot/DataJpaTestIntegrationSpec.groovy, spock-spring/boot-test/src/test/groovy/org/spockframework/boot/SpringBootTestAnnotationIntegrationSpec.groovy, spock-spring/boot-test/src/test/groovy/org/spockframework/boot/WebMvcTestIntegrationSpec.groovy, spock-spring/src/main/java/org/spockframework/spring/SpringExtension.java
I've added more robust support for the current Spring-Boot 1.4 test annotations (#581) by checking for annotations on the spec, which class itself contains an `@BootstrapWith` annotation. 
This works for `@SpringBootTest `, `@DataJpaTest` and `@WebMvcTest`. 
I've also refactored the `SpringExtension` class a bit to reflect which check determines the presence of Spring-Boot. It might be possible to clean up this class even more, but I'm not entirely sure if some checks are needed for backwards compatibility with older Spring versions.
=> Fixed #581 by adding complete Spring-Boot 1.4 support

spock-core/src/main/java/org/spockframework/runtime/extension/builtin/MethodRuleInterceptor.java, spock-core/src/main/java/org/spockframework/runtime/extension/builtin/RuleExtension.java, spock-specs/src/test/groovy/org/spockframework/smoke/junit/JUnitMethodRuleOrder.groovy, spock-specs/src/test/groovy/org/spockframework/smoke/junit/JUnitTestRuleOrder.groovy
MethodRules did not wrap setup() and cleanup(). Only the feature method
was wrapped. 
Since I don't know the Spock codebase well enough, I was only able to create a testcase to show the bug. After that, I debugged the code and tried to watch for the difference between TestRule and MethodRule. 
I found the RuleExtension with it's difference. Changing the MethodRule extension to do the same as the TestRule extension resulted in a NullPointerException, since in that case `invocation.getMethod().getReflection()` is null.
Again, using the debugger I found `invocation.getIteration().getParent().getFeatureMethod().getReflection()`. But I am not sure, if this is a valid fix. 
Fixes #584
=> fix MethodRule execution

docs/getting_started.adoc
There is a line break between the URI and the caption of the link. This breaks the link in Asciidoctor and in the Github preview. This commit rearranges the line breaks so that this issue is resolved.
=> Fix broken hyperlink

spock-spring/src/main/java/org/spockframework/spring/SpringMockTestExecutionListener.java
If the application contexts has some bean definitions that are abstract, currently the method 
`applicationContext.getBean(beanName)` throws the exception `org.springframework.beans.factory.BeanIsAbstractException` (Error creating bean with name '...': Bean definition is abstract).
So it is needed to check if the beanDefinition is abstract before getting the bean.
=> Fix to avoid Spring BeanIsAbstractException at attaching mocks in SpringMockTestExecutionListener

settings.gradle, spock-spring/boot-test/boot-test.gradle
Since 1.4.0.RELEASE the spring-boot-gradle plugin requires at least
Java 7 so we decided to follow this version requirement for this
subproject.
=> Change boot-test to only execute when Java 7 or higher is available

README.md
It works only with GitHub Flavoured Markdown but not for others. %20 would be more general.
=> Replace spaces in readme links with %20

build.gradle
The SingningExtension will try to load the key if the signing.password
property is set, even if no actual signing is required. This happens
as soon as the property is present regardless of its value.
=> Fix NPE for install task if SIGNING_PASSWORD is null

build.gradle
The tasks `uploadArchives`, `publishJavadoc`, `publishDocs`,
and `tagRelease` should only be performed by travis on the `master` or
for tags.
=> Remove all publishing from shippableCiBuild and fix javadoc timestamps

spock-core/src/main/java/org/spockframework/runtime/ConditionFailedWithExceptionError.java, spock-core/src/main/java/org/spockframework/runtime/SpockRuntime.java, spock-core/src/main/java/org/spockframework/runtime/extension/builtin/FailsWithInterceptor.java, spock-specs/src/test/groovy/org/spockframework/smoke/condition/ExceptionsInConditions.groovy, spock-specs/src/test/groovy/org/spockframework/smoke/extension/FailsWithExtension.groovy, spock-specs/src/test/groovy/org/spockframework/smoke/extension/ReportLogExtensionSpec.groovy
Introduce `ConditionFailedWithExceptionError` as new subclass
of `ConditionNotSatisfiedError` it is thrown if an exception
occurred during evaluation of an assertion. `@FailsWith`
now handles this special case by looking also at the cause
of `ConditionFailedWithExceptionError`.
=> Refactor handling of Exceptions in assertions

build.gradle, spock-core/core.gradle, spock-core/src/main/java/org/spockframework/mock/runtime/ByteBuddyClassCache.java, spock-core/src/main/java/org/spockframework/mock/runtime/ByteBuddyInterceptorAdapter.java, spock-core/src/main/java/org/spockframework/mock/runtime/ByteBuddyInvoker.java, spock-core/src/main/java/org/spockframework/mock/runtime/ByteBuddyMethodInvoker.java, spock-core/src/main/java/org/spockframework/mock/runtime/ProxyBasedMockFactory.java, spock-report/report.gradle, spock-specs/specs.gradle, spock-specs/src/test/groovy/org/spockframework/smoke/mock/MockProxyCaching.groovy
Adds support for generating classes using Byte Buddy instead of cglib when Byte Buddy is found on the class path. (Other than on *AppVeyor*, running `:spock-specs:test` works fine on my machine.)
=> Added support for mock class creation using Byte Buddy

.travis.yml
Those directories seem to cause cache rebuilding everytime (~15-20 seconds extra build time). To be verified looking at the PR builds that Gradle needs less time to recompile those scripts.
=> Reduce cache rebuilding on Travis

spock-spring/boot-test/src/main/java/org/spockframework/boot/service/ScopedHelloWorldService.java, spock-spring/boot-test/src/test/groovy/org/spockframework/boot/SimpleBootAppIntegrationSpec.groovy, spock-spring/boot-test/src/test/groovy/org/spockframework/boot/SpringBootTestAnnotationIntegrationSpec.groovy, spock-spring/src/main/java/org/spockframework/spring/SpringMockTestExecutionListener.java
Test framework should not try to access a scopedTarget bean directly.
=> Add support for scoped beans

build.gradle, spock-core/core.gradle, spock-core/src/main/java/org/spockframework/mock/runtime/ProxyBasedMockFactory.java
This makes sure that if methods that are declared by super classes and by interfaces are always public. Java defines that a class always inherits from its super class first and only from interfaces if a method is not declared by a class. If the class method defines a visibility less than public, the method would not be visible.
=> Update to Byte Buddy 1.5

docs/data_driven_testing.adoc
Fix docs to correspond with values "7 | 4 || 7" in MathSpec
=> Fix data_driven_testing.adoc

spock-core/src/main/groovy/spock/util/matcher/IsCloseTo.groovy, spock-core/src/main/java/org/spockframework/mock/IMockFactory.java, spock-core/src/main/java/org/spockframework/util/IMultiset.java, spock-guice/src/test/groovy/org/spockframework/guice/IService1.groovy, spock-guice/src/test/groovy/org/spockframework/guice/IService2.groovy, spock-guice/src/test/groovy/org/spockframework/guice/Service2.groovy, spock-specs/src/test.java1.8/java/org/spockframework/smoke/mock/IDeposit.java, spock-specs/src/test/groovy/org/spockframework/junit/JUnitRuleBehavior.groovy, spock-specs/src/test/groovy/org/spockframework/smoke/GroovyCallChain.groovy, spock-specs/src/test/groovy/org/spockframework/smoke/extension/Fast.groovy, spock-specs/src/test/groovy/org/spockframework/smoke/extension/Slow.groovy, spock-specs/src/test/groovy/org/spockframework/smoke/junit/JUnitCompliance.groovy, spock-specs/src/test/groovy/org/spockframework/smoke/mock/GroovyMocksForGroovyClasses.groovy, spock-specs/src/test/groovy/org/spockframework/smoke/mock/GroovyMocksForInterfaces.groovy, spock-spring/src/test/groovy/org/spockframework/spring/IService2.groovy, spock-spring/src/test/groovy/org/spockframework/spring/MockInjectionWithEmbeddedConfig.groovy, spock-spring/src/test/groovy/org/spockframework/spring/Service1.groovy, spock-spring/src/test/groovy/org/spockframework/spring/docs/DetachedJavaConfig.groovy, spock-spring/src/test/groovy/org/spockframework/spring/docs/GreeterService.groovy, spock-tapestry/src/test/java/org/spockframework/tapestry/IService1.java, spock-tapestry/src/test/java/org/spockframework/tapestry/IService2.java, spock-tapestry/src/test/java/org/spockframework/tapestry/IService3.java
This pull request removes redundant `public` and `static` modifiers where it is possible.
In case of Java, only interfaces were cleaned up. While in Groovy all unnecessary modifiers were removed.
[Java Specification](https://docs.oracle.com/javase/specs/jls/se7/html/jls-9.html):
>Every field declaration in the body of an interface is implicitly `public`, `static`, and `final`. It is permitted to redundantly specify any or all of these modifiers for such fields.
[Groovy documentation](http://groovy-lang.org/style-guide.html#_public_by_default):
>By default, Groovy considers classes and methods public. So you don’t have to use the public modifier everywhere something is public.
=> Redundant `static` and `public` modifiers

build.gradle, spock-core/src/main/java/org/spockframework/runtime/ConfigurationScriptLoader.java
Hi, a PR for supporting later versions of Groovy. We are currently wanting to move Groovy master to 3.0.0 but have held back since we currently use some Spock tests in some of the modules.
Locally when testing this I changed the baseVersion to 1.2 but didn't include that in the PR as I am not sure what your plans are in that regard. Perhaps it is time for a 1.1 branch and this could go on a master branch along with things like PR#632?
At the moment there aren't any breaking changes in master that we are aware of, so I didn't make another variant. (There is possibly a change in 2.4.10 which impacts Spock but that is another issue - run the Spock build using 2.4.10 and see test failures if you want details).
We are however about to merge a bunch of largish features into later branches, so …
=> support later groovy versions including 3.0+

build.gradle
At least a try to fix it. However, it helped in [Mockito](https://github.com/mockito/mockito/commit/d45fecfabc98a0f5d972886dd0541cdb69b41ca4) and micro-infra-spring to get rid of that issues after switching to container-based architecture.
Error message:
Process 'Gradle Test Executor 23' finished with non-zero exit value 137
Related Travis issue: https://github.com/travis-ci/travis-ci/issues/5582
=> Fix issue with aborted build on Travis

.travis.yml, README.md, appveyor.yml, build.gradle, shippable.yml, spock-bom/bom.gradle
Test results are now put into a folder that includes the test task name
to prevent two different test tasks to override each others result, and
thus requiring a rebuild instead of staying up-to-date.
Also replaced deprecated task.leftShift with doLast
=> Add code coverage with jacoco and codecov.io

spock-core/src/main/java/org/spockframework/runtime/ExpressionInfoValueRenderer.java, spock-specs/src/test/groovy/org/spockframework/smoke/condition/ConditionRenderingSpec.groovy, spock-specs/src/test/groovy/org/spockframework/smoke/condition/StringComparisonRendering.groovy
This fixes some bugs that were introduced in #706:
The length check in renderAsFailedStringComparison did overflow, so we need to cast it to long first. Also add some more info when the OOM protection kicks in. Furthermore, decrease the the memory limit from
1mb to 50kb. And add some specs for tryReduceStringSizes.
=> Fix ExpressionInfoValueRenderer.renderAsFailedStringComparison overflow

docs/module_spring.adoc
Current URL linked on "boot examples" on http://spockframework.org/spock/docs/1.1/modules.html (waaaaay down at the bottom) gives a 404.
Current URL (404): https://github.com/spockframework/spock/tree/master/spock-spring/src/test/groovy/org/spockframework/spring/boot-test
Correct URL: https://github.com/spockframework/spock/tree/master/spock-spring/boot-test/src/test/groovy/org/spockframework/boot
=> Fix URL to Spring Boot examples.

spock-core/src/main/java/org/spockframework/compiler/ConditionRewriter.java
Since EmptyStatement will be made singleton, its constructor will be removed soon, so use EmptyStatement.INSTANCE instead to get the instance.
https://github.com/apache/groovy/blob/fa3c2719c594ca7710e976dd5330a2e442713551/src/main/org/codehaus/groovy/ast/stmt/EmptyStatement.java#L40
=> Use EmptyStatement.INSTANCE to get the instance

build.gradle, spock-core/core.gradle, spock-guice/guice.gradle, spock-report/report.gradle, spock-spring/spring.gradle, spock-tapestry/tapestry.gradle, spock-unitils/unitils.gradle
JUnit 5 already did it, so it cannot hurt to add it to spock as well. https://github.com/junit-team/junit5/issues/866
@sormuras you created the PR for JUnit5 and ota4j would you mind reviewing this PR?
One thing to note is that spock uses the `spock.lang` package for the public api, and the `org.spockframework` package for the implementation, so a common super package is not possible without breaking up the jars. I opted to use `org.spockframework` for core and `org.spockframework.<module>` for the extensions.
=> Add JPMS module name definition in MANIFEST.MF

docs/release_notes.adoc, spock-core/src/main/java/org/spockframework/mock/runtime/MockConfiguration.java, spock-specs/src/test/groovy/org/spockframework/smoke/mock/JavaSpies.groovy
=> Improve `constructorArgs` for spies can now accept a map directly

docs/interaction_based_testing.adoc
This PR implements the documentation enhancement that was proposed in #733
=> Explicit documentation on Code argument constraints return type

spock-core/src/main/java/org/spockframework/mock/IMockConfiguration.java, spock-core/src/main/java/org/spockframework/mock/IMockObject.java, spock-core/src/main/java/org/spockframework/mock/runtime/ByteBuddyMethodInvoker.java, spock-core/src/main/java/org/spockframework/mock/runtime/CglibRealMethodInvoker.java, spock-core/src/main/java/org/spockframework/mock/runtime/CompositeMockFactory.java, spock-core/src/main/java/org/spockframework/mock/runtime/GroovyMockFactory.java, spock-core/src/main/java/org/spockframework/mock/runtime/JavaMockFactory.java, spock-core/src/main/java/org/spockframework/mock/runtime/JavaMockInterceptor.java, spock-core/src/main/java/org/spockframework/mock/runtime/MockObject.java, spock-core/src/main/java/org/spockframework/util/ReflectionUtil.java, spock-specs/src/test/groovy/org/spockframework/smoke/mock/JavaSpies.groovy, spock-spring/src/main/java/org/spockframework/spring/mock/DelegatingInterceptor.java
=> Rework spying on concrete instances

docs/interaction_based_testing.adoc
Also 2 minor enhancements with `MockDetector` and ByteBuddy.
Closes #608.
=>  [#608] Switch mock creation to simpler 1.1 syntax in documentation

spock-core/src/main/java/org/spockframework/mock/runtime/ProxyBasedMockFactory.java, spock-specs/src/test/groovy/org/spockframework/smoke/mock/MockingAndBridgeMethods.groovy, spock-specs/src/test/java/org/spockframework/smoke/mock/DiscountedItem.java, spock-specs/src/test/java/org/spockframework/smoke/mock/DiscountedPublicItem.java, spock-specs/src/test/java/org/spockframework/smoke/mock/Item.java, spock-specs/src/test/java/org/spockframework/smoke/mock/PublicItem.java
fixes #122, resolves #135
cherry picked from commit 9d8de4a and modified to work with ByteBuddy
=> Intercept bridge methods that override concrete methods in a supertype

docs/extensions.adoc, docs/release_notes.adoc, spock-core/src/main/java/org/spockframework/runtime/extension/builtin/RetryBaseInterceptor.java, spock-core/src/main/java/org/spockframework/runtime/extension/builtin/RetryConditionContext.java, spock-core/src/main/java/org/spockframework/runtime/extension/builtin/RetryIterationInterceptor.java, spock-core/src/main/java/spock/lang/IgnoreIf.java, spock-core/src/main/java/spock/lang/Requires.java, spock-core/src/main/java/spock/lang/Retry.java, spock-specs/src/test/groovy/org/spockframework/smoke/extension/RetryFeatureExtensionSpec.groovy
The `@Retry` annotation can now be used to configure an optional `condition` closure that is evaluated when a feature fails to determine whether it should be retried.
Resolves #872.
=> Allow to configure retry condition

docs/release_notes.adoc, spock-core/src/main/java/org/spockframework/runtime/extension/builtin/RetryIterationInterceptor.java, spock-specs/src/test/groovy/org/spockframework/smoke/extension/RetryFeatureExtensionSpec.groovy
When using `Retry.Mode.{SETUP_FEATURE_CLEANUP, FEATURE}`, a failed iteration always made a test fail even when a retry was successful.
Fixes #876.
=> Ensure successful retry makes test succeed

build.gradle
In the `-groovy-2.5` variant.
Preferably to be merged before the final Spock 1.2 version is released. As Spock uses `groovy-*` modules as dependency it is less convenient to override the version in your end project.
=> Upgrade Groovy to 2.5.2

.travis.yml, build.gradle, gradle/wrapper/gradle-wrapper.properties, settings.gradle, spock-specs/src/test/groovy/org/spockframework/EmbeddedSpecification.groovy, spock-specs/src/test/groovy/org/spockframework/smoke/extension/IgnoreIfExtension.groovy, spock-specs/src/test/groovy/org/spockframework/smoke/extension/RequiresExtension.groovy
Hi,
I did some work on #808 and I can compile Spock with JDK 10. There are several important things though:
* Tapestry 5 is not ready for JDK9+ (https://issues.apache.org/jira/projects/TAP5/issues/TAP5-2588)
* Compilation on JDK 11+ fails due to #843 (see #865)
Regards,
Martin
=> Spock can be compiled on JDK 10 [WIP]

spock-core/src/main/java/org/spockframework/runtime/extension/builtin/StepwiseExtension.java
=> StepwiseExtension: Mark only subsequent features as skipped after failure

docs/release_notes.adoc, spock-core/src/main/java/org/spockframework/runtime/SpockRuntime.java, spock-specs/src/test/groovy/org/spockframework/smoke/WithBlocks.groovy, spock-specs/src/test/groovy/org/spockframework/verifyall/VerifyAllSpecification.groovy
=> Fix void methods with implicit targets failing in `with` and `verifyAll`

build.gradle, spock-core/core.gradle
It is needed only to start the Groovy console and should not pollute the compile classpath with the number of transitive dependencies:
```
+--- org.spockframework:spock-core:1.2-RC1-groovy-2.5
|    +--- org.codehaus.groovy:groovy:2.5.0
|    +--- org.codehaus.groovy:groovy-groovysh:2.5.0 <----------- HERE
|    |    +--- org.codehaus.groovy:groovy:2.5.0
|    |    +--- org.codehaus.groovy:groovy-cli-picocli:2.5.0
|    |    |    +--- org.codehaus.groovy:groovy:2.5.0
|    |    |    \--- info.picocli:picocli:3.0.2
|    |    +--- org.codehaus.groovy:groovy-console:2.5.0
|    |    |    +--- org.codehaus.groovy:groovy:2.5.0
|    |    |    +--- org.codehaus.groovy:groovy-cli-picocli:2.5.0 (*)
|    |    |    +--- org.codehaus.groovy:groovy-swing:2.5.0
|    |    |    |    \--- …
```
=> Exclude groovy-groovysh dependency

build.gradle, spock-core/src/main/java/org/spockframework/mock/codegen/CodegenDummy.java, spock-core/src/main/java/org/spockframework/mock/codegen/Target.java, spock-core/src/main/java/org/spockframework/mock/runtime/ProxyBasedMockFactory.java, spock-specs/src/test/groovy/org/spockframework/smoke/extension/IgnoreIfExtension.groovy, spock-specs/src/test/groovy/org/spockframework/smoke/extension/RequiresExtension.groovy
In order to create mock objects on Java 11, `ProxyBasedMockFactory` now uses ByteBuddy's `Lookup`-based `ClassLoadingStrategy`, if available.
Resolves #843.
=> Use Lookup class loading strategy if available

build.gradle, settings.gradle, spock-report/report.gradle, spock-specs/mock-integration/mock-integration.gradle, spock-specs/mock-integration/src/test/groovy/MockingIntegrationSpec.groovy, spock-spring/spring.gradle
The new project contains integration tests for using Spock to mock Java
interfaces/classes with cglib/byte-buddy and objenesis, and without any
of them.
In addition, the old testCglib task is removed because it is no longer
necessary to rerun all tests with byte-buddy deactivated.
=> Add :spock-specs:mock-integration subproject

spock-core/src/main/java/org/spockframework/mock/runtime/ByteBuddyMockFactory.java, spock-core/src/main/java/org/spockframework/mock/runtime/CglibMockFactory.java, spock-core/src/main/java/org/spockframework/mock/runtime/DynamicProxyMockFactory.java, spock-core/src/main/java/org/spockframework/mock/runtime/ProxyBasedMockFactory.java
This refactoring commit extracts three top-level classes from
`ProxyBasedMockFactory`: one for generating dynamic proxies for
interfaces, one for cglib-specific code, and one for ByteBuddy-specific
code.
=> Separate code specific to cglib/ByteBuddy

spock-core/src/main/java/spock/mock/MockingApi.java
This commit adds Groovy annotations that help IDEs to support type
inference when a class and a closure is specified to create a stub,
mock, or spy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/920)
=> Improve IDE type inference in MockingApi

spock-core/core.gradle
Avoid java.lang.NoSuchMethodError: net.bytebuddy.dynamic.loading.ClassInjector$UsingLookup.isAvailable() - method introduced in version 1.8.0
Used here:
https://github.com/spockframework/spock/blame/master/spock-core/src/main/java/org/spockframework/mock/runtime/ByteBuddyMockFactory.java#L103
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/926)
=> Updated net.bytebuddy version

internal-backport/internal-backport.gradle, internal-backport/src/main/java/groovy/transform/NamedParam.java, internal-backport/src/main/java/groovy/transform/NamedParams.java, settings.gradle, spock-core/core.gradle, spock-core/src/main/java/spock/mock/MockingApi.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/921)
=> Add NamedParam support for gradle-2.5 with backport to 2.4

spock-core/src/main/java/org/spockframework/runtime/Condition.java, spock-specs/src/test/groovy/org/spockframework/smoke/condition/ConditionRendering.groovy
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/931)
=> Fix erroneous regex where an optional colon was defined instead of a non-capturing group

spock-core/src/main/java/org/spockframework/runtime/StackTraceFilter.java, spock-specs/src/test/groovy/org/spockframework/smoke/StackTraceFiltering.groovy
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/933)
=> Filter Java 9+ reflection stack frames and properly escape dots in the filter regex

spock-core/src/main/java/org/spockframework/runtime/FailedEqualityComparisonRenderer.java, spock-specs/src/test/groovy/org/spockframework/smoke/condition/EqualityComparisonRendering.groovy
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/934)
=> Use canoncial class name in comparison failure results if present, as they are usually more readable

docs/spock_primer.adoc
The ordered list illustrates the invocation order a little better than
only having it in the paragraph above.
The additional heading makes finding this a lot easier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/949)
=> Improve documentation on fixture invocation order

gradle/publishMaven.gradle, spock-bom/bom.gradle
Prior to this commit, spock-bom was using `components.java`
unnecessarily. As a side-effect, `spock-bom-*.jar.asc` was published
alongside the POM.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/951)
=> Don't publish jar signature artifacts for spock-bom

spock-core/src/main/java/org/spockframework/runtime/MethodSelectorResolver.java, spock-core/src/main/java/org/spockframework/runtime/ParameterizedFeatureNode.java, spock-core/src/main/java/org/spockframework/runtime/SimpleFeatureNode.java, spock-core/src/main/java/org/spockframework/runtime/SpecNode.java
The `SpockHelloWorldTest` failed because each `FeatureNode` was of type `CONTAINER` and had an `IterationNode` as child. Appearently when a `CONTAINER` node is skipped, it does not generate any test event that show up in the summary of the unit test.
There are two cases:
* A `SimpleFeatureNode` represents the test itself. It should not have any children, thus it is of type `TEST` (a _leaf_ node in the tree). It delegates to an `IterationNode` without having it as a child.
* A `ParametrizedFeatureNode` represents both a container and (probably) a test itself. It can have zero or more `IteratioNode`s and the test results in all children summarize the test itself. This it should be either of type `CONTAINER` or `CONTAINER_AND_TEST`.
Additionally I added the possiblity to skip a whole …
=> Spock 2.0 fix skipped test count

docs/spock_primer.adoc
Example before a fix cannot be compiled because there is used GString and $ have special meaning so we need escape $.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1052)
=> fix $ escaping in spock_primer.adoc

spock-core/src/main/java/org/spockframework/compiler/SpecRewriter.java, spock-specs/src/test/groovy/org/spockframework/smoke/AnonymousInnerClasses.groovy
I have a test like
```groovy
def '#testee.getClass().simpleName should have #aliases #expectedAliases'() {
expect:
testee.aliases == expectedAliases
where:
testee                || expectedAliases
new BaseCommand() { } || [testee.getClass().typeName[(testee.getClass().package.name.length() + 1)..-1].uncapitalize()]
and:
aliases = expectedAliases.size() == 1 ? 'alias' : 'aliases'
}
```
which runs fine with Java 8, but with Java 11 I get
```
Illegal method name "#testee.getClass().simpleName should have #aliases #expectedAliases" in class net/kautler/command/api/CommandTest$1
java.lang.ClassFormatError: Illegal method name "#testee.getClass().simpleName should have #aliases #expectedAliases" in class net/kautler/command/api/CommandTest$1
at …
```
=> Fix anonymous inner classes

spock-core/src/main/java/org/spockframework/mock/runtime/ByteBuddyMockFactory.java
According to [JLS 4.7.8](https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html#jvms-4.7.8)
> A class member that does not appear in the source code must be marked using a Synthetic attribute,
> or else it must have its ACC_SYNTHETIC flag set. The only exceptions to this requirement are
> compiler-generated methods which are not considered implementation artifacts, namely the instance
> initialization method representing a default constructor of the Java programming language (§2.9),
> the class initialization method (§2.9), and the Enum.values() and Enum.valueOf() methods.
So I'd say it makes sense to mark the `$spock_interceptor` field as synthetic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Make the $spock_interceptor field synthetic

spock-core/src/main/java/org/spockframework/compiler/ConditionRewriter.java, spock-core/src/main/java/org/spockframework/compiler/ExpressionReplacingVisitorSupport.java
This propery was not brought over previously.
This works fine for Groovy 2, as the meta class can find the synthetic constructor that is generated for the anonymous inner class.
With Groovy 3 this changed, so without this fix, rewritten anonymous inner class instantiations cannot be executed as the meta class does not find the synthetic constructor anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1078)
=> Transport isUsingAnonymousInnerClass property when transforming constructor call expressions

spock-core/src/main/java/org/spockframework/compiler/SpecParser.java
Before Groovy 1.7 the Groovy compiler generated constructor was marked as synthetic.
In Groovy 1.7.* this was changed and the constructor was not distinguishable so Peter
added recognition logic based on parameter count, visibility, contained statements
and whether joint compilation is done.
In Groovy 1.8 though the constructor is marked with the new property `hasNoRealSourcePosition`
and in Groovy 3 the constructor is additionally annotated with a `@Generated` annotation.
This PR removes the recognition logic and the synthetic check as the minimum Groovy version is 2
and replaces it by checking the `hasNoRealSourcePosition` property which will work properly
with Groovy 2 and Groovy 3 alike.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> Improve recognition of Groovy compiler generated constructors

.travis.yml
To speed up the things before the M2 release.
Java 13 is not currently compatible with the used Gradle version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1088)
=> Reduce number of builds in Travis to 8 and 11

spock-core/src/main/java/spock/util/environment/Jvm.java, spock-specs/src/test/groovy/org/spockframework/smoke/extension/IgnoreIfExtension.groovy, spock-specs/src/test/groovy/org/spockframework/smoke/extension/RequiresExtension.groovy, spock-specs/src/test/groovy/spock/util/JvmSpec.groovy
Added flexible support for Java 13+. Removed methods for unsupported Java versions (`<8`).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1068)
=> Modernize Jvm structure in conditional test execution

build.gradle, spock-core/core.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1082)
=> Use new Console main class for Groovy 3+

docs/interaction_based_testing.adoc, spock-core/src/main/java/org/spockframework/mock/runtime/MockInstantiator.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1020)
=> Mention Byte Buddy as cglib alternative in the documentation

spock-specs/src/test/groovy/org/spockframework/docs/interaction/InteractionDocSpec.groovy
The previous comment was obviously a copy paste mistake.
Mentioning the fact that endsWith comes from Hamcrest is also a good idea in my opinion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1097)
=> Fix comment on code example

spock-core/src/main/java/org/spockframework/mock/runtime/ByteBuddyMethodInvoker.java, spock-core/src/main/java/org/spockframework/mock/runtime/CglibRealMethodInvoker.java, spock-core/src/main/java/org/spockframework/runtime/ErrorSpecNode.java, spock-core/src/main/java/org/spockframework/runtime/GroovyRuntimeUtil.java, spock-core/src/main/java/org/spockframework/util/ExceptionUtil.java, spock-core/src/main/java/org/spockframework/util/ReflectionUtil.java, spock-spring/src/main/java/org/spockframework/spring/mock/DelegatingInterceptor.java
There is no need to separate `sneakyThrow` and `doSneakyThrow`, it can be done
in one declaration.
I also added a return type so it can be used in methods or lambdas that need a return value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1077)
=> Improve ExceptionUtil.sneakyThrow declaration

build.gradle, spock-core/core.gradle, spock-specs/specs.gradle, spock-spring/boot-test/boot-test.gradle, spock-spring/boot2-test/boot2-test.gradle, spock-spring/spring.gradle, spock-unitils/unitils.gradle
Spock shouldn't provide the other to do not pollute the classpath.
It's common practice nowadays to exclude transitive dependencies,
which is not good as "spock-groovy2-compat" is needed with Groovy 2.
Proposed `realase notes` entry:
```
=== Breaking Changes
==== Reduce number of transitive Groovy dependencies to just groovy.jar
Spock started to provide only one Groovy dependency - `groovy.jar`. The others,
in the majority of cases were not needed in the end projects and were only polluting classpath
(or excluded explicitly). If other Groovy dependencies are needed in the project,
they have to be provided explicitly.
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock …
=> Reduce number of Groovy dependencies to just groovy.jar

build.gradle
To do not prevent people from playing with Groovy 4.x when alpha is released.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1108)
=> Switch maxGroovyVersion to 4.x for snapshots

build.gradle
In some cases. `buildTime` used in all JARs' manifest caused all subprojects to be rebuilt and retested.
```
$ gw clean check
...
BUILD SUCCESSFUL in 1m 20s
70 actionable tasks: 68 executed, 2 up-to-date
```
No changes:
```
$ gw check
...
BUILD SUCCESSFUL in 1m 15s
54 actionable tasks: 32 executed, 22 up-to-date
```
Change in spock-spec (all tests in that module are re-executed):
```
$ gw check
...
BUILD SUCCESSFUL in 1m 19s
54 actionable tasks: 32 executed, 22 up-to-date
```
```
$ gw clean check
...
BUILD SUCCESSFUL in 1m 20s
70 actionable tasks: 68 executed, 2 up-to-date
```
No changes:
```
$ gw check
...
BUILD SUCCESSFUL in 1s
54 actionable tasks: 54 up-to-date
```
Change in spock-spec (all tests in that module are re-executed):
```
$ gw check
...
BUILD SUCCESSFUL in 39s
54 actionable …
```
=> Speed up local build greatly

build.gradle
I realize that there might be 3.0.3 before M3, but with that change people using the snapshot of Spock (or local builds) can have Groovy 3 with [better](http://groovy-lang.org/changelogs/changelog-3.0.1.html) JDK9+ support by default.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1125)
=> Upgrade Groovy to 3.0.2

spock-core/src/main/java/org/spockframework/compiler/WhereBlockRewriter.java, spock-specs/src/test/groovy/org/spockframework/smoke/parameterization/DataProviders.groovy
They are not necessary for Groovy and there is a problem with missing line numbers in stack traces.
Alternative solution would have been to set the source information on the return statement.
If you for example had
```groovy
def foo() {
expect: true
where: a << b
}
```
then the `MissingPropertyException` complaining about `b` had no line information in the stack trace.
See also https://issues.apache.org/jira/browse/GROOVY-9440
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1116)
=> Set source position for return statement in data provider method

build.gradle, docs/release_notes.adoc, spock-core/src/main/groovy/spock/util/EmbeddedSpecRunner.groovy, spock-specs/src/test/groovy/org/spockframework/smoke/FeatureMethods.groovy, spock-specs/src/test/groovy/org/spockframework/smoke/extension/PendingFeatureExtensionSpec.groovy, spock-specs/src/test/groovy/org/spockframework/smoke/extension/RequiresExtension.groovy, spock-specs/src/test/groovy/org/spockframework/smoke/parameterization/DataTables.groovy, spock-specs/src/test/groovy/org/spockframework/smoke/parameterization/UnrolledFeatureMethods.groovy, spock-testkit/src/test/groovy/spock/platform/SpockHelloWorldTest.java
This replaces workaround in M2 for JUnit 5.6 compatibility (fixes #1073). As a side effect Spock will no longer be compatible with JUnit 5.5 (but it is better to be compatible with incoming 5.7).
Some tests in the @Vampire changes with unrolling could be affected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1107)
=> Upgrade to JUnit 5.6.1 and 4.13

docs/data_driven_testing.adoc, docs/migration_guide.adoc, docs/release_notes.adoc, spock-core/src/main/java/org/spockframework/compiler/AstUtil.java, spock-core/src/main/java/org/spockframework/compiler/DeepBlockRewriter.java, spock-core/src/main/java/org/spockframework/compiler/SpecRewriter.java, spock-core/src/main/java/org/spockframework/compiler/SpockTransform.java, spock-core/src/main/java/org/spockframework/compiler/WhereBlockRewriter.java, spock-core/src/main/java/org/spockframework/runtime/PlatformParameterizedSpecRunner.java, spock-core/src/main/java/org/spockframework/runtime/SpecInfoBuilder.java, spock-core/src/main/java/org/spockframework/runtime/model/DataProviderInfo.java, spock-core/src/main/java/org/spockframework/runtime/model/DataProviderMetadata.java, spock-specs/src/test/groovy/org/spockframework/docs/datadriven/DataSpec.groovy, spock-specs/src/test/groovy/org/spockframework/smoke/parameterization/DataTables.groovy, spock-specs/src/test/groovy/org/spockframework/smoke/parameterization/InvalidWhereBlocks.groovy, spock-specs/src/test/groovy/org/spockframework/smoke/parameterization/Parameterizations.groovy
The implementation of previous data table column access is a bit sub-optimal.
It has various bugs and hard to grasp quirks.
Some of them are:
- If you had a derived data variable before the table, the injection of the previous data providers didn't work properly,
as the position was counted from the previous data variables, but for derived data variables there is no data provider,
so the calculated indexes / lenghts were off by amount of derived data variables before the data table or data pipe
- Referencing the previous columns in a later column only works in some situations, but not in others.
If you for example use the previous column inside a closure, it is not found, as the reference was not
properly defined for the closure
- Referencing a previous derived data variable never works …
=> Fix previous data table column access and block access from and to data pipes

docs/extensions.adoc, docs/release_notes.adoc, spock-core/src/main/java/org/spockframework/compiler/AstNodeCache.java, spock-core/src/main/java/org/spockframework/compiler/WhereBlockRewriter.java, spock-core/src/main/java/org/spockframework/runtime/SpecInfoBuilder.java, spock-core/src/main/java/org/spockframework/runtime/model/DataProcessorMetadata.java, spock-core/src/main/java/org/spockframework/runtime/model/FeatureInfo.java, spock-core/src/main/java/org/spockframework/runtime/model/FeatureMetadata.java, spock-specs/src/test/groovy/org/spockframework/runtime/extension/builtin/UnrollIterationNameProviderSpec.groovy, spock-specs/src/test/groovy/org/spockframework/smoke/parameterization/MethodParameters.groovy
- Do not fail data provider calling due to different order between data variables and method parameters (#651)
- Inject data variables by name, instead of order and have the correct argument array length initially (#651)
Fixes #651
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1105)
=> Remove requirement to have data-driven method arguments in the same order as in the where block (#651)

docs/data_driven_testing.adoc, docs/extensions.adoc, docs/release_notes.adoc, spock-core/src/main/java/org/spockframework/compiler/WhereBlockRewriter.java, spock-core/src/main/java/org/spockframework/runtime/PlatformSpecRunner.java, spock-core/src/main/java/org/spockframework/runtime/extension/IMethodInvocation.java, spock-core/src/main/java/org/spockframework/runtime/extension/MethodInvocation.java, spock-core/src/main/java/org/spockframework/runtime/model/MethodInfo.java, spock-specs/src/test/groovy/org/spockframework/smoke/parameterization/MethodParameters.groovy
Fixes #652
Only last commit to be reviewed.
With this PR, you no longer are required to provide all or no data variables as parameters.
You are also no longer required that all parameters are data variables.
So you can now specify some or all data variables in any order and also additional parameters that get injected by some extension eventually.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1114)
=>  Do not require all data variables as parameters (#652) 

spock-core/src/main/java/org/spockframework/runtime/ErrorSpecNode.java, spock-specs/src/test/groovy/org/spockframework/runtime/ErrorSpecNodeSpec.groovy, spock-testkit/src/test/groovy/spock/platform/SpockHelloWorldTest.java, spock-testkit/src/test/groovy/spock/testkit/testsources/ErrorTestCase.groovy
As the `ErrorSpecNode` is neither of type `TEST` or `CONTAINER_AND_TEST` and
does not have test descendents, the default prune algorithm throws it away.
That means, that the whole spec is simply ignored if there was an error, like
when having an exception in an `@IgnoreIf` closure.
When running all tests, the spec simply does not occur, when running the spec or
a feature in the spec that contains the exception you get "no tests found", no
matter whether you run through IntelliJ runner or through Gradle.
By overwriting the `prune()` method with an empty one, the pruning is disabled
for this node as also documented in its JavaDoc and the error will be reported
properly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Do not prune ErrorSpecNodes

build.gradle, docs/release_notes.adoc, spock-junit4/src/test/groovy/org/spockframework/smoke/groovy/UsageOfDeprecatedNotYetImplemented.groovy, spock-specs/specs.gradle, spock-specs/src/test3.0/groovy/org/spockframework/smoke/UsageOfNotYetImplemented.groovy
They requires Groovy 3.0.3 to pass, see:
https://issues.apache.org/jira/browse/GROOVY-9492
Fixes #1127. It also closes #1067 which I fixed at the Groovy side in 3.0.3.
To do not generate separate PR I also bumbed Groovy 2.5.8 to 2.5.11 for better Java 14+ support.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1150)
=> Add tests for new groovy.test.NotYetImplemented

spock-core/src/main/java/org/spockframework/compiler/SpecParser.java, spock-core/src/main/java/org/spockframework/compiler/SpecRewriter.java, spock-core/src/main/java/org/spockframework/compiler/WhereBlockRewriter.java, spock-core/src/main/java/org/spockframework/compiler/model/Block.java, spock-core/src/main/java/org/spockframework/gentyref/TypeToken.java, spock-core/src/main/java/org/spockframework/mock/runtime/ByteBuddyMockFactory.java, spock-core/src/main/java/org/spockframework/mock/runtime/GroovyMockFactory.java, spock-core/src/main/java/org/spockframework/runtime/AsyncRunListener.java, spock-core/src/main/java/org/spockframework/runtime/AsyncStandardStreamsListener.java, spock-core/src/main/java/org/spockframework/runtime/ExpressionInfoRenderer.java, spock-core/src/main/java/org/spockframework/runtime/RunContext.java, spock-core/src/main/java/org/spockframework/runtime/SpecInfoBuilder.java, spock-core/src/main/java/org/spockframework/runtime/SpecRunHistory.java, spock-core/src/main/java/org/spockframework/runtime/model/ExpressionInfo.java, spock-core/src/main/java/org/spockframework/runtime/model/SpecInfo.java, spock-core/src/main/java/org/spockframework/util/AbstractMultiset.java, spock-core/src/main/java/org/spockframework/util/CollectionUtil.java, spock-core/src/main/java/org/spockframework/util/Filter.java, spock-core/src/main/java/org/spockframework/util/HashMultiset.java, spock-core/src/main/java/org/spockframework/util/LinkedHashMultiset.java, spock-core/src/main/java/org/spockframework/util/Matchers.java, spock-core/src/main/java/org/spockframework/util/Pair.java, spock-core/src/main/java/org/spockframework/util/ReflectionUtil.java, spock-specs/src/test3.0/groovy/org/spockframework/smoke/lamba/LambdaSpec.groovy
Working on #1128 my eyes was irritated by the (sensible) Idea warnings in `SpecInfoBuilder` related to sorting and the usage of lambdas/method references instead of anonymous classes. As Spock 2 requires Java 8+ it can be improved.
To simplify it and do it in a batch I applied Java 8 (and Java 7 along the way) basic refactorings suggested by Idea in spock-core. I ran through them briefly and they look ok. All tests still pass.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1138)
=> Some Java 8 related automatic refactorings

docs/known_issues.adoc, docs/release_notes.adoc, spock-core/src/main/java/org/spockframework/compiler/SpockTransform.java, spock-core/src/main/java/org/spockframework/util/VersionChecker.java, spock-specs/src/test/groovy/org/spockframework/runtime/GlobalExtensionRegistrySpec.groovy, spock-specs/src/test/groovy/org/spockframework/util/VersionCheckerSpec.groovy
In production Spock version. For early adopters of the further Groovy
versions (such as 4.x). And to use in the Groovy 4.x build itself - instead of the snapshot version.
Before Spock 2.0-M1 people were able to use only 1.3-SNAPSHOT with Groovy 3, even though, in the majority of cases, it just worked.
If you have a good idea how to test it in a better way, please let me know.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1164)
=> Ability to disable Groovy version check

docs/extensions.adoc, docs/release_notes.adoc, spock-core/src/main/java/org/spockframework/compiler/AstNodeCache.java, spock-core/src/main/java/org/spockframework/compiler/SpecAnnotator.java, spock-core/src/main/java/org/spockframework/runtime/ExtensionRunner.java, spock-core/src/main/java/org/spockframework/runtime/extension/RepeatedExtensionAnnotations.java, spock-core/src/main/java/org/spockframework/runtime/model/NodeInfo.java, spock-specs/src/test/groovy/org/spockframework/smoke/extension/RepeatableLocalExtensionsSpec.groovy
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1118)
=> Add support for repeatable annotations for local extensions (#1030)

docs/extensions.adoc, docs/release_notes.adoc, spock-core/src/main/java/spock/lang/Issue.java, spock-specs/src/test/groovy/org/spockframework/docs/extension/IssueDocSpec.groovy, spock-specs/src/test/groovy/org/spockframework/smoke/extension/IssueExtension.groovy
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1189)
=> Make @Issue repeatable (#1030)

spock-core/src/main/java/org/spockframework/compiler/ConditionRewriter.java, spock-core/src/main/java/org/spockframework/compiler/ExpressionReplacingVisitorSupport.java, spock-core/src/main/java/org/spockframework/runtime/ExpressionInfoConverter.java, spock-specs/src/test3.0/groovy/org/spockframework/smoke/ArrayInitializer.groovy
fixes #1202
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1203)
=> Fix NullPointerException with array initializers (#1202)

spock-core/src/main/java/org/spockframework/compiler/AstNodeCache.java, spock-core/src/main/java/org/spockframework/compiler/AstUtil.java, spock-core/src/main/java/org/spockframework/compiler/ConditionRewriter.java, spock-core/src/main/java/org/spockframework/compiler/InteractionRewriter.java, spock-core/src/main/java/org/spockframework/compiler/SpecRewriter.java, spock-core/src/main/java/org/spockframework/compiler/SpockTransform.java, spock-core/src/main/java/org/spockframework/compiler/WhereBlockRewriter.java, spock-specs/src/test/groovy/org/spockframework/smoke/NameClashes.groovy, spock-spring/src/test/groovy/org/spockframework/spring/ScopedBeans.groovy
This happened due to a buggy VariableScopeVisitor as reported in https://issues.apache.org/jira/browse/GROOVY-9651
fixes #1200 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1201)
=> Fix name clashes where variables that are named like method calls destroy the method call (#1200)

build.gradle
The dependency hamcrest-core is deprecated. The right artifact name is just hamcrest.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1181)
=> Fix Hamcrest dependency

docs/extensions.adoc, spock-specs/src/test/groovy/org/spockframework/docs/extension/TempDirDocSpec.groovy
- Replace "temp directory" by "temporary directory" in plain prose
- Slightly improve wording
- Be more precise about non-@Shared fields resulting in one temp-dir per feature
  and/or iteration
- Update formatting width to 120 characters like in the rest of Spock's ADOCs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1213)
=> Improve 'TempDir' extension documentation

docs/all_in_one.adoc, docs/faq.adoc, docs/index.adoc
For now, there are two FAQ items explaining optional dependencies in general and
explaining why there are two class mocking variants ByteBuddy vs. CGLIB.
Closes #1165.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1212)
=> Add FAQ to documentation

.travis.yml, build.gradle, settings.gradle, spock-core/src/main/java/org/spockframework/util/VersionChecker.java
Also added the correnspnding Travis build.
The build fails with:
```
> Task :spock-core:verifyOSGi FAILED
Resolution failed. Capabilities satisfying the following requirements could not be found:
[<<INITIAL>>]
⇒ osgi.identity: (osgi.identity=spock-core)
⇒ [spock-core version=2.0.0.groovy-30-SNAPSHOT]
⇒ osgi.wiring.package: (osgi.wiring.package=org.w3c.dom)
```
on OpenJDK 15. @rotty3000 How would it best way to deal with that?
(with the OSGI check disabled it builds fine with updated dependencies)
=> Bump dependencies for Java 15 build

build.gradle, docs/extensions.adoc, docs/release_notes.adoc, spock-core/src/main/java/org/spockframework/runtime/extension/builtin/ConditionalExtension.java, spock-core/src/main/java/org/spockframework/runtime/extension/builtin/PreconditionContext.java, spock-core/src/main/java/org/spockframework/runtime/extension/builtin/RetryBaseInterceptor.java, spock-core/src/main/java/org/spockframework/runtime/extension/builtin/RetryConditionContext.java, spock-core/src/main/java/org/spockframework/util/MopUtil.java, spock-specs/src/test/groovy/org/spockframework/smoke/extension/IgnoreIfExtension.groovy, spock-specs/src/test/groovy/org/spockframework/smoke/extension/PendingFeatureIfExtensionSpec.groovy, spock-specs/src/test/groovy/org/spockframework/smoke/extension/RequiresExtension.groovy, spock-specs/src/test/groovy/org/spockframework/smoke/extension/RetryFeatureExtensionSpec.groovy
fixes #1177
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1204)
=> Increase Groovy version to 3.0.6 and give condition closures access to the specification instance

.idea/vcs.xml
This configures a visible right margin at column 80 and word wrap for the commit
dialogue in IntelliJ IDEA.
=> IDEA settings, vcs.xml: add CommitMessageInspectionProfile

.idea/vcs.xml
This PR is meant to improve the merged PR #1246.
---
I just noticed strange unstaged changes in _vcs.xml_ after I pulled the new master. They seem to originate in your suggested changes and look like this:
What the diff basically say is:
* The commit message word-wrap width of 72 characters is the default, which is why it gets removed by IDEA automatically.
* The last line feed in the file should be obligatory, but IDEA seems to prefer to always save the file without one.
I did not notice that at first when accepting the changes via GitHub UI or maybe they came up after a recent IDEA update on my machine, but now I cannot switch branches because of uncommitted changes in that file anymore. In my own projects I never commit any IDE config files, but Spock has some, which is why I suggested …
=> vcs.xml: Remove explicit default line length limit 72

spock-core/src/main/java/org/spockframework/runtime/extension/builtin/ExecutionExtension.java, spock-core/src/main/java/org/spockframework/runtime/extension/builtin/IsolatedExtension.java, spock-core/src/main/java/org/spockframework/runtime/extension/builtin/ResourceLockChildrenExtension.java, spock-core/src/main/java/org/spockframework/runtime/extension/builtin/ResourceLockExtension.java, spock-specs/src/test/groovy/org/spockframework/smoke/extension/ParallelSpec.groovy
=> Make parallel extensions support inheritance

spock-junit4/src/main/java/org/spockframework/junit4/ExceptionAdapterExtension.java, spock-junit4/src/test/groovy/org/spockframework/junit4/junit/ExceptionAdapterSpec.groovy
=> Fix ExceptionAdapterExtension to also handle inherited fixture methods

spock-core/src/main/java/org/spockframework/runtime/extension/builtin/RetryExtension.java, spock-core/src/main/java/org/spockframework/runtime/extension/builtin/RetryIterationInterceptor.java, spock-specs/src/test/groovy/org/spockframework/smoke/extension/RetryFeatureExtensionSpec.groovy
This change fixes two issues with `SETUP_FEATURE_CLEANUP` mode of
`RetryExtension` when used with data-driven unrolled features:
- Only the first failed iteration was being retried, the rest were
not executed, although they were all being reported as failed.
- The reporting of failed iterations was incorrect - the failure was
being attributed to the next iteration, or the containing feature if
the failing iteration happened to be the last one.
Fixes: #1267
=> Fix Retry extension behavior for unrolled tests

docs/release_notes.adoc, spock-core/src/main/java/org/spockframework/mock/runtime/BaseMockInterceptor.java, spock-core/src/main/java/org/spockframework/mock/runtime/GroovyMockInterceptor.java, spock-core/src/main/java/org/spockframework/mock/runtime/JavaMockInterceptor.java, spock-specs/src/test/groovy/org/spockframework/smoke/mock/GroovyMocksForGroovyClasses.groovy
=> Fix handling of `is` as getter for boolean properties on GroovyMocks

docs/extensions.adoc, docs/modules.adoc
Including the junit 4 module seemed to be required for us to upgrade our project to Spock 2.0.
=> Update Rule and ClassRule documentation with Junit 4 module link.

.github/workflows/release.yml, build.gradle
Remove build avoidance, as we now have build-caching with gradle enterprise the build on the tag should be fast.
Disable tagging and pushing for the time being as the automatic GITHUB_TOKEN won't trigger workflows,
for now we will use manual tags.
fixes #1304
=> Simplify release workflow

README.md
I added information that Groovy 3.0 is recommended. In addition, I replaced broken links (which could be restored once Cloudfare extends the number of available subdomains with TLS).
Definitely the webconsole is problematic:
> Powered by Groovy 2.4.1 and Spock 1.0
Maybe it should be also removed until updated (if at all)?
=> Adjust README content to Spock 2.0

spock-core/src/main/java/org/spockframework/compiler/SpecRewriter.java, spock-specs/src/test/groovy/org/spockframework/smoke/CleanupBlocks.groovy, spock-specs/src/test/groovy/org/spockframework/smoke/ast/CleanupBlocksAstSpec.groovy, spock-specs/src/test/groovy/org/spockframework/smoke/ast/condition/ExceptionConditionsAstSpec.groovy, spock-specs/src/test/groovy/org/spockframework/smoke/condition/ExceptionConditions.groovy
=> Fix regression with multi-assignment of method call result

spock-core/src/main/java/org/spockframework/runtime/ErrorSpecNode.java, spock-specs/src/test/groovy/org/spockframework/runtime/ErrorSpecNodeSpec.groovy
As the ErrorSpecNode does not have children it would get removed
when trying to select specific tests methods
For example, gradle will report that no test were found,
and not report the actual error.
=> Prevent removal of ErrorSpecNode from execution hierarchy

spock-core/src/main/java/org/spockframework/runtime/extension/builtin/ConditionalExtension.java, spock-specs/src/test/groovy/org/spockframework/smoke/extension/IgnoreIfExtension.groovy, spock-specs/src/test/groovy/org/spockframework/smoke/extension/RequiresExtension.groovy
This allows access to static methods when `@IgnoreIf`, `@Requires` and `@PendingFeatureIf` is used on a Specification.
We already set the owner when a Feature is annotated.
=> Set the owner for condition closures on spec annotations

spock-core/src/main/java/org/spockframework/runtime/extension/builtin/ConditionalExtension.java, spock-core/src/main/java/org/spockframework/runtime/extension/builtin/PreconditionContext.java, spock-specs/src/test/groovy/org/spockframework/smoke/extension/IgnoreIfExtension.groovy, spock-specs/src/test/groovy/org/spockframework/smoke/extension/RequiresExtension.groovy
ConditionalExtensions can now access shared fields via `shared.`.
If applied on the Specification level, this causes the shared field initializers
and `setupSpec` methods to run.
If a ConditionalExtension applied on the Specification level uses `instance.` it
will now behave as if it was applied on every feature.
=> Add "shared." support to ConditionalExtensions

README.md, spock-core/src/main/java/org/spockframework/runtime/extension/builtin/IgnoreIfExtension.java, spock-core/src/main/java/org/spockframework/runtime/extension/builtin/RequiresExtension.java, spock-core/src/main/java/spock/lang/IgnoreIf.java, spock-core/src/main/java/spock/lang/Requires.java, spock-specs/src/test/groovy/org/spockframework/smoke/extension/IgnoreIfExtension.groovy, spock-specs/src/test/groovy/org/spockframework/smoke/extension/RequiresExtension.groovy
Fixes https://github.com/spockframework/spock/issues/1361
=> Add optional reason to Requires and IgnoreIf

spock-junit4/src/main/java/org/spockframework/junit4/AbstractRuleInterceptor.java, spock-junit4/src/test/groovy/org/spockframework/junit4/junit/JUnitClassRules.groovy, spock-junit4/src/test/groovy/org/spockframework/junit4/junit/JUnitMethodRuleOrder.groovy, spock-junit4/src/test/groovy/org/spockframework/junit4/junit/JUnitRules.groovy, spock-junit4/src/test/groovy/org/spockframework/junit4/junit/JUnitTestRuleOrder.groovy
Prior to this commit the rules were executed in the wrong order.
When rules we used in both parent and child classes,
then the rules in the child classes were executed before those of the parent class.
Fixes #1050
=> Fix JUnit rule run order

.github/workflows/branches-and-prs.yml, .github/workflows/codeql-analysis.yml, .github/workflows/release.yml
This simplifies the caching configuration, but is less specific and looses the separation between 2.5 and 3.0 builds. WDYT?
=> Use actions/setup-java@v2 built-in caching for gradle

spock-core/src/main/java/org/spockframework/runtime/extension/builtin/TempDirExtension.java, spock-specs/src/test/groovy/org/spockframework/smoke/extension/TempDirExtensionSpec.groovy
I've bumped into that in one of my projects.
A variant of previously fixed:
https://github.com/spockframework/spock/issues/1229
Btw, I assume that support for regular `static` fields hasn't been implemented in that extension purposely, right?
=> Fix @TempDir not working for @Shared "inherited" fields

spock-core/src/main/java/org/spockframework/runtime/ClassSelectorResolver.java, spock-testkit/src/test/groovy/spock/platform/SpockEngineBase.java, spock-testkit/src/test/groovy/spock/platform/SpockHelloWorldTest.java
Prior to this commit the callback that is called when an entire test
class is selected enabled all feature methods on the wrong `SpecInfo`
instance which was part of the closure.
=> Fix selector ordering issue

spock-core/src/main/java/org/spockframework/runtime/MethodSelectorResolver.java, spock-core/src/main/java/org/spockframework/runtime/PlatformParameterizedSpecRunner.java, spock-core/src/main/java/org/spockframework/runtime/model/FeatureInfo.java, spock-core/src/main/java/org/spockframework/runtime/model/IterationFilter.java, spock-specs/src/test/groovy/org/spockframework/runtime/model/IterationFilterSpec.groovy, spock-testkit/src/test/groovy/spock/platform/SpockHelloWorldTest.java, spock-testkit/src/test/groovy/spock/testkit/testsources/UnrollTestCase.groovy
Individual iterations can now be selected via their unique ID.
Co-authored-by: Leonard Brünings <lbruenings@gradle.com>
=> Add support for selecting individual iterations

docs/utilities.adoc, spock-core/src/main/java/org/spockframework/compiler/AstNodeCache.java, spock-core/src/main/java/org/spockframework/compiler/ConditionRewriter.java, spock-core/src/main/java/org/spockframework/runtime/FailedSetEqualityComparisonRenderer.java, spock-core/src/main/java/org/spockframework/runtime/SpockRuntime.java, spock-core/src/main/java/org/spockframework/runtime/model/ExpressionInfo.java, spock-core/src/main/java/org/spockframework/util/Assert.java, spock-specs/src/test/groovy/org/spockframework/docs/utilities/CollectionConditions.groovy, spock-specs/src/test/groovy/org/spockframework/smoke/ast/condition/CollectionConditionAstSpec.groovy, spock-specs/src/test/groovy/org/spockframework/smoke/condition/CollectionConditionRendering.groovy
=> Add collection conditions

spock-core/src/main/java/org/spockframework/mock/CannotCreateMockException.java
I faced occurrence of `CannotCreateMockException` in my project.
Its error message was like `Cannot create mock for class myPackage.MyClassnull`.
I think `MyClassnull` in the message should be split into two words, `MyClass` and `null` for understandability.
=> Add single space into CannotCreateMockException message

docs/module_spring.adoc, docs/modules.adoc
For each Spock extension module, now the documentation explicitly mentions their group IDs and artifact names, also linking to the corresponding artifact at Maven Central. Before, users were struggling sometimes, and it was not easily possible to point them to the Spock manual.
See e.g. https://stackoverflow.com/a/70917526/1082681. Quote:
> We are missing one dependency here 
> ```groovy
> testImplementation group: 'org.spockframework', name: 'spock-spring', version: '2.1-M2-groovy-3.0'
> ```
> Which basically makes it possible to write tests in Spock and use spring test context. 
> 
> (...) it took me 4 hours to discover (very sad face) ://
=> Mention extension module artifacts in documentation

settings.gradle, spock-spring/spring6-test/spring6-test.gradle, spock-spring/spring6-test/src/test/groovy/org/spockframework/spring6/NoMockConfig.groovy, spock-spring/spring6-test/src/test/groovy/org/spockframework/spring6/RuntimeCompatibilitySpec.groovy, spock-spring/spring6-test/src/test/groovy/org/spockframework/spring6/SpringBeanTest.groovy, spock-spring/spring6-test/src/test/groovy/org/spockframework/spring6/SpringRunnerTest.java, spock-spring/spring6-test/src/test/groovy/org/spockframework/spring6/TestConfig.groovy, spock-spring/src/main/java/org/spockframework/spring/mock/BackwardsCompatibleInstantiationAwareBeanPostProcessorAdapter.java, spock-spring/src/main/java/org/spockframework/spring/mock/SpockMockPostprocessor.java
=> Fix Spring 6 incompatibility

spock-core/src/main/java/org/spockframework/runtime/ErrorSpecNode.java, spock-specs/src/test/groovy/org/spockframework/runtime/ErrorSpecNodeSpec.groovy
Fixes #1444.
At the moment, `SpockEngineDiscoveryPostProcessor#processSpecNode` creates an `ErrorSpecNode` (which implements `org.junit.platform.engine.TestDescriptor`) after catching errors thrown by extensions, which is then silently discarded by Maven Surefire because it filters for `testPlan.containsTests()`. Therefore, we have to make sure that `containsTests` returns `true`. An easy way to do that is to override `mayRegisterTests()`. Another way would be to override `isTest()` instead, but actually neither an error node nor a spec actually _is_ as test, they rather can contain tests.
=> Prevent removal of ErrorSpecNode by Maven

spock-core/src/main/java/org/spockframework/runtime/IterationNode.java, spock-specs/src/test/groovy/org/spockframework/smoke/parameterization/ParameterizedFeatureNodeStatuses.groovy
Prior to this commit, any exception thrown in IterationNode.around(), i.e. in an iteration interceptor,
would pollute the feature context, affecting the outcome of subsequent iterations and the feature itself.
fixes #1441
=> Fix context pollution in IterationNode.around()

settings.gradle
com.gradle.enterprise                              3.10
com.gradle.common-custom-user-data-gradle-plugin   1.6.5
org.asciidoctor.jvm.convert                        3.3.2
net.nemerosa.versioning                            2.15.1
io.github.gradle-nexus.publish-plugin to           1.1.0
com.github.ben-manes.versions                      0.42.0
biz.aQute.bnd.builder                              6.2.0
org.gradle.test-retry                              1.3.2
=> Update Gradle plugins

spock-core/src/main/java/org/spockframework/runtime/extension/builtin/ConfineMetaClassChangesInterceptor.java
If `@ConfineMetaClassChanges` is used on a data-driver feature method, the
`ConfineMetaClassChangesInterceptor` is shared between iterations of the
method. Clear the `originalMetaClasses` field of the interceptor after
each invocation to avoid populating the list with duplicate references
to original meta-classes.
The previous implementation was not defective _per se_, but this fixes a
potential efficiency issue (determined by how many meta-classes are
stored and how many iterations of the feature method are run).
=> Discard unnecessary state in ConfineMetaClassChangesInterceptor

spock-core/core.gradle, spock-junit4/junit4.gradle, spock-specs/specs.gradle
All Jetbrains annotations have retention policy `CLASS`.
Accroding to [Jetbrains repo](https://github.com/JetBrains/java-annotations#using-the-annotations) recommended way to include them in gradle project is:
```groovy
dependencies {
compileOnly 'org.jetbrains:annotations:23.0.0'
}
```
testCompileOnly for `spock-junit4` and `spock-specs`
=> Removed runtime dependency on Jetbrains Annotations

spock-spring/src/main/java/org/spockframework/spring/EnableSharedInjection.java
Quick fix for https://github.com/spockframework/spock/issues/1471
Based on the release notes from [2.0.0-M5](https://spockframework.org/spock/docs/2.0/release_notes.html#_misc_2), it looks like the `EnableSharedInjection` annotation should be public.
While the annotation appears to work as expected despite being package-private, it does produce some noisy IDE warnings that are worth getting rid of.
This doesn't seem to affect the tests in `org.spockframework.spring.SharedFieldsInjection`. I don't think it merits a test of its own, but I could be wrong.
=> Make EnableSharedInjection public

spock-core/src/main/java/org/spockframework/runtime/FeatureNode.java, spock-core/src/main/java/org/spockframework/runtime/extension/builtin/TagExtension.java, spock-core/src/main/java/org/spockframework/runtime/model/FeatureInfo.java, spock-core/src/main/java/org/spockframework/runtime/model/ITestTaggable.java, spock-core/src/main/java/org/spockframework/runtime/model/TestTag.java, spock-core/src/main/java/spock/lang/Tag.java, spock-specs/src/test/groovy/org/spockframework/runtime/model/TestTagTest.groovy, spock-specs/src/test/groovy/org/spockframework/smoke/extension/TagExtension.groovy, spock-testkit/src/test/groovy/spock/platform/InheritedTest.java, spock-testkit/src/test/groovy/spock/platform/SpockHelloWorldTest.java, spock-testkit/src/test/groovy/spock/platform/TagCompatibilityTest.groovy, spock-testkit/src/test/groovy/spock/testkit/testsources/ChildTagSpec.groovy, spock-testkit/src/test/groovy/spock/testkit/testsources/SimpleTagSpec.groovy
=> Add junit-platform TestTag support

spock-core/src/main/java/org/spockframework/runtime/DataIterator.java, spock-core/src/main/java/org/spockframework/runtime/DataIteratorFactory.java, spock-core/src/main/java/org/spockframework/runtime/IDataIterator.java, spock-core/src/main/java/org/spockframework/runtime/ParameterizedFeatureChildExecutor.java, spock-core/src/main/java/org/spockframework/runtime/ParameterizedFeatureNode.java, spock-core/src/main/java/org/spockframework/runtime/PlatformParameterizedSpecRunner.java, spock-core/src/main/java/org/spockframework/runtime/SpockExecutionContext.java, spock-core/src/main/java/org/spockframework/runtime/extension/IDataDriver.java, spock-core/src/main/java/org/spockframework/runtime/extension/IIterationRunner.java, spock-core/src/main/java/org/spockframework/runtime/model/ExecutionResult.java, spock-core/src/main/java/org/spockframework/runtime/model/FeatureInfo.java, spock-core/src/main/java/org/spockframework/runtime/model/MethodInfo.java, spock-core/src/main/java/org/spockframework/runtime/model/ParameterInfo.java, spock-specs/src/test/groovy/org/spockframework/runtime/ClosingOfDataProviders.groovy, spock-specs/src/test/groovy/org/spockframework/runtime/EstimatedNumberOfIterations.groovy
The main motivation is to extract the `DataIterator` logic from the 
`PlatformParameterizedSpecRunner` into a reusable form, so that it can
serve as foundation for data driven specs in the future.
This also opened up the possibility of adding a new extension point `IDataDriver`,
which can be used to control the actual iterations of a feature.
A possible use-case is to enable property based testing like jqwik
via a third-party extension.
=> Introduce DataIterator and IDataDriver

.gitignore, build-logic/asciidoc-extensions/asciidoc-extensions.gradle
Copy the local to `.asciidoctor/lib`, so that the IntelliJ Asciidoctor
plugin can pick it up. This can be done manually by calling the
`installAsciidocExtension` task on the `asciidoc-extensions` project,
or simply by triggering the `idea` task.
=> Make the asciidoc extension available to IJ plugin

spock-spring/src/main/java/org/spockframework/spring/mock/SpockMockPostprocessor.java, spock-spring/src/test/groovy/org/spockframework/spring/mock/SpringBeanOverridesPrimaryBeanSpec.groovy, spock-spring/src/test/groovy/org/spockframework/spring/mock/SpringBeanWIthSinglePrimaryBeanSpec.groovy, spock-spring/src/test/groovy/org/spockframework/spring/mock/SpringBeanWithManyOrNoPrimarySpec.groovy, spock-spring/src/test/groovy/org/spockframework/spring/mock/SpringSpyForCircularBeansSpec.groovy
fixes #1502
When the context contains multiple beans for given interface
but one of them is marked as @Primary it should be possible
to mock this interface.
Current implementation doesn't check if one of found beans is primary
and fails with an exception.
My change mirrors a similar logic used in spring-boot-starter-test
and resolves this issue.
=> Make @SpringMock work for beans with @Primary

docs/spock_primer.adoc, spock-core/src/main/java/org/spockframework/runtime/SpecInfoBuilder.java, spock-specs/src/test/groovy/org/spockframework/runtime/model/SpecInfoSpec.groovy
=> Validate uniqueness of fixture methods per specification class

spock-core/src/main/java/org/spockframework/mock/runtime/DynamicProxyMockInterceptorAdapter.java, spock-core/src/main/java/org/spockframework/mock/runtime/ObjectMethodInvoker.java, spock-specs/src/test/groovy/org/spockframework/smoke/mock/PartialMockingInterfacesWithDefaultMethods.groovy
=> Fix issue with Object methods on interface spies

README.adoc
Hello!
I have noticed that in the `README.adoc` file, there is a link to contributing page that does not work. I've noticed that the extension of the file has changed from `CONTRIBUTING.md` to `CONTRIBUTING.adoc`, but the readme was not changed accordingly.
This PR fixes it.
=> Fix contributing link in README

gradle/publishMaven.gradle
The sourceUrl for the deps are `github.spockframework.org/spock` which cannot be resolved so I have changed it to poin to this repo `github.com/spockframework/spock`.
=> fix: change sourceUrl

spock-core/src/main/java/spock/lang/Execution.java, spock-specs/src/test/groovy/org/spockframework/smoke/extension/RetryFeatureExtensionSpec.groovy
To explain - without using a comment - why a non-default execution mode is used.
Occasionally, I had to use the construction similar to the following when a reason could be not obvious.
```groovy
@Execution(ExecutionMode.SAME_THREAD) // because test is using static fields
class MyTestWithStaticFields extends Specification {
...
}
```
WDYT?
=> Extends @Execution with optional "reason" field

build.gradle, settings.gradle, spock-core/core.gradle, spock-guice/guice.gradle, spock-junit4/junit4.gradle, spock-specs/mock-integration/mock-integration.gradle, spock-specs/specs.gradle, spock-spring/boot2-test/boot2-test.gradle, spock-spring/boot3-test/boot3-test.gradle, spock-spring/spring.gradle, spock-spring/spring3-test/spring3-test.gradle, spock-spring/spring5-test/spring5-test.gradle, spock-spring/spring6-test/spring6-test.gradle, spock-tapestry/tapestry.gradle, spock-testkit/testkit.gradle, spock-unitils/unitils.gradle
https://docs.gradle.org/8.0/userguide/declaring_dependencies.html#sec:type-safe-project-accessors
=> Enable type-safe project accessors

docs/extensions.adoc, spock-core/src/main/java/org/spockframework/runtime/ExtensionRunner.java, spock-core/src/main/java/org/spockframework/runtime/extension/IAnnotationDrivenExtension.java, spock-core/src/main/java/org/spockframework/runtime/extension/IMethodInvocation.java, spock-core/src/main/java/org/spockframework/runtime/extension/MethodInvocation.java, spock-core/src/main/java/org/spockframework/runtime/extension/ParameterResolver.java, spock-core/src/main/java/org/spockframework/runtime/model/MethodInfo.java, spock-core/src/main/java/org/spockframework/runtime/model/ParameterInfo.java, spock-core/src/main/java/org/spockframework/util/Assert.java, spock-specs/src/test/groovy/org/spockframework/docs/extension/ParameterInjectionSpec.groovy
Extension authors can now create annotation driven extensions, that target method parameters.
=> Add annotation extensions for parameters

spock-specs/src/test/groovy/org/spockframework/smoke/parameterization/MethodParameters.groovy
The interceptor used in the test did not call proceed().
Due to that there was never any failure even if the test
condition should not hold.
=> Fix broken test

spock-core/src/main/java/spock/util/concurrent/PollingConditions.java
`(assert)` works just fine in Clojure, no reason to avoid it. :wink:
=> Fix a typo in JavaDoc

docs/spock_primer.adoc, spock-specs/src/test/groovy/org/spockframework/docs/utilities/ConditionBlockSpec.groovy
This adds a new section about @ConditionBlock usage into the Conditions. The ConditionBlockSpec is used as a code sample.
This fixes #1242
=> Document @ConditionBlock Annotation in the Guide

docs/utilities.adoc, spock-specs/src/test/groovy/org/spockframework/docs/utilities/OldMethodSpec.groovy
This adds a new section about old() into the utilities. The OldMethodSpec was added as a code sample for the usage.
This fixes #1228
=> Document old-Method in the Guide

gradle/libs.versions.toml, spock-guice/guice.gradle, spock-specs/mock-integration/mock-integration.gradle, spock-spring/spring3-test/spring3-test.gradle, spock-spring/spring5-test/spring5-test.gradle
Since jacoco 0.8.9 it does not open the java.lang package anymore, so we need to do that on our own.
See "Agent should not open java.lang package to unnamed module of the application class loader"
https://github.com/jacoco/jacoco/pull/1334
=> Open java.base/java.lang for ALL-UNNAMED for cglib users

gradle/libs.versions.toml, spock-core/src/main/java/org/spockframework/runtime/GroovyRuntimeUtil.java, spock-specs/src/test/groovy/org/spockframework/smoke/mock/JavaMocksForGroovyClasses.groovy
This adds a test case to reproduce the "false" behavior of 
mockMe.getProperty("bar") in Groovy 4.0.7 and onwards.
=> Added Groovy 4.0.7 test case for getProperty call

spock-specs/src/test/groovy/org/spockframework/mock/Issue520Repository.java, spock-specs/src/test/groovy/org/spockframework/mock/MockSpecInfoAnnotationSpec.groovy, spock-specs/src/test/groovy/spock/util/concurrent/BlockingVariablesSpec.groovy
The method `GenericTypeReflectorUtil.getReturnType()` now also tries to resolve TypeVariable, if these have bounds like the method:
`<T extends Annotation> T getAnnotation()`
Which now returns `Annotation` as return type instead of `Object`.
This was actually implemented with:
Replace gentyref code with geantyref library #1743.
This fixes #1163 "NodeInfo#getAnnotation returns instance of Cglib-generated that does not actually implement Annotation".
It also fixes #520 "Better support for generic return types with Stub()".
=> GenericTypeReflectorUtil.getReturnType() now resolves type variables

spock-core/src/main/java/org/spockframework/runtime/RunContext.java
Prior to this commit, `RunContext` used a plain `ThreadLocal`,
which caused a new `RunContext` being created for every thread.
With this change, child threads will inherit the `RunContext` stack
of their parent thread and fork it for their use.
=> Make RunContext use InheritableThreadLocal

config/nohttp/allowlist.lines, spock-spring/src/test/resources/org/spockframework/spring/docs/MockDocu-context.xml
:spock-spring:spring4CgLibTest>DetachedXmlExample
fails with:
"Cannot find the declaration of element 'beans'."
Relates to #1735
=> Fix flaky Spring tests due to schema resolution

spock-core/src/main/java/org/spockframework/mock/runtime/ByteBuddyMockFactory.java, spock-core/src/main/java/org/spockframework/mock/runtime/ProxyBasedMockFactory.java, spock-specs/src/test/groovy/org/spockframework/mock/runtime/ByteBuddyMockFactoryConcurrentSpec.groovy, spock-specs/src/test/groovy/org/spockframework/mock/runtime/ByteBuddyTestClassLoader.java
Changed locking scheme in ByteBuddyMockFactory from a single global lock CACHE to cacheLocks with size 16. 
The used TypeCachingLock from cacheLocks depends on the hashcode of TypeCache.SimpleKey, 
which aggregates the types to mock.
The old global CACHE lock did block Threads regardless, if they try to mock the same type or not.
This is a similar fix as in Mockito:
[Mockito 3095](https://github.com/mockito/mockito/pull/3095)
=> Use multiple locks in ByteBuddyMockFactory to reduce lock contention

docs/interaction_based_testing.adoc, spock-specs/src/test/groovy/org/spockframework/docs/interaction/GlobalMockDocSpec.groovy
Added test case base documentation for global mocks. And clarify the usage of the global mock and lifecycle.
This fixes #785
=> Clarify Documentation for global Mocks

spock-core/src/main/java/org/spockframework/mock/runtime/GroovyMockFactory.java, spock-specs/src/test/groovy/org/spockframework/smoke/mock/GroovyMocks.groovy
Previous to this commit, it was possible to create a global
GroovyMock/Stub/Spy for a type that was already a global mock,
this is problematic and leaked the modified meta-class.
=> Add check to prevent double global mocking

spock-core/src/main/java/org/spockframework/mock/runtime/BaseMockInterceptor.java, spock-core/src/main/java/org/spockframework/mock/runtime/GroovyMockFactory.java, spock-core/src/main/java/org/spockframework/mock/runtime/GroovyMockInterceptor.java, spock-core/src/main/java/org/spockframework/mock/runtime/JavaMockFactory.java, spock-core/src/main/java/org/spockframework/mock/runtime/JavaMockInterceptor.java, spock-core/src/main/java/org/spockframework/mock/runtime/StaticMockMethod.java, spock-core/src/main/java/org/spockframework/util/GenericTypeReflectorUtil.java, spock-specs/src/test/groovy/org/spockframework/mock/AdditionalInterfaceResponseSpec.groovy, spock-specs/src/test/groovy/org/spockframework/util/GenericTypeReflectorUtilSpec.groovy
The metaClass used in JavaMocks of Groovy classes did not contain the methods of additionalInterfaces, so the fix is to change the MetaClass, if we are a GroovyObject and have additionalInterfaces to the mocked MetaClass. It is not the best solution, because we now use the MetaClass of the Mock, which also contains methods and interfaces of Spock internal, but there is currently no class implementing mockType + additionalInterfaces. This would be a bigger rework.
The second fix is for the JavaMock of a Java class with additionalInterfaces. Previously the mockType of the Java class was used also for the methods of the additionalInterfaces, which lead to a NullPointerException.
This fixes #1405
=> Defining responses for additionalInterfaces doesn't work

spock-core/src/main/java/org/spockframework/runtime/extension/builtin/PreconditionContext.java, spock-core/src/main/java/org/spockframework/runtime/extension/builtin/RetryConditionContext.java, spock-core/src/main/resources/dsld/spock_tests.dsld, spock-core/src/main/resources/org/spockframework/idea/spock.gdsl
Prior to this commit `@Requires`, `@IgnoreIf`, `@PendingFeatureIf`, and `@Retry`
didn't have any IDE support for the condition closure.
=> Add GDSL/DSLD for ConditionalExtension's annotations

spock-core/src/main/java/org/spockframework/runtime/PlatformParameterizedSpecRunner.java, spock-core/src/main/java/org/spockframework/runtime/extension/IDataDriver.java, spock-core/src/main/java/org/spockframework/runtime/extension/builtin/RepeatUntilFailureExtension.java, spock-specs/src/test/groovy/org/spockframework/smoke/parameterization/MethodParameters.groovy
The iteration info holds a list of the data values for the current iteration.
The data driver logic had an error where it gave all parameter infos
to the data driver instead of only the ones representing data variables.
Data drivers only deal with data variables, not with additional arguments that
are supplied by extensions. Due to that the data values in the iteration info
had additional MISSING_ARGUMENT entries for the additional arguments which
then also broke things like unroll patterns, conditional annotations accessing data
values and so on
=> Fix too many arguments being set as data values in iteration info

docs/release_notes.adoc, spock-core/src/main/java/org/spockframework/compiler/DeepBlockRewriter.java, spock-specs/src/test/groovy/org/spockframework/smoke/AccessingOldValues.groovy
Previously if you had multiple arguments to an `old(...)` call 2nd and on were simply ignored,
and if you had no argument the compiler throws a `NullPointerException`.
Now the compiler validates that there is exactly one argument to an `old(...)` call.
Due to the multiple arguments now being forbidden, this is theoretically a breaking change,
but until recently the whole feature was not even documented and probably very few people
use it at all, let alone with multiple arguments.
=> Validate argument amount in old(...) calls

.github/actions/setup-build-env/action.yml, .github/workflows/branches-and-prs.yml, .github/workflows/codeql-analysis.yml, .github/workflows/release.yml
Adapt to recommended usage of gradle/gradle-build-action, i.e.,
only call it once, and use ./gradlew for Gradle calls instead of
the arguments parameter.
=> Update gradle-build-action usage

build.gradle, docs/extensions.adoc, gradle/libs.versions.toml, spock-core/src/main/java/org/spockframework/mock/runtime/CglibMockMaker.java, spock-core/src/main/java/org/spockframework/mock/runtime/IMockMaker.java, spock-core/src/main/java/org/spockframework/mock/runtime/mockito/MockitoMockMaker.java, spock-core/src/main/java/org/spockframework/mock/runtime/mockito/MockitoMockMakerImpl.java, spock-core/src/main/java/org/spockframework/mock/runtime/mockito/MockitoMockMakerSettings.java, spock-core/src/main/java/spock/mock/MockMakers.java, spock-specs/mock-integration/mock-integration.gradle, spock-specs/src/test/groovy/org/spockframework/docs/extension/MockMakerConfigurationDocSpec.groovy, spock-specs/src/test/groovy/org/spockframework/docs/interaction/MockMakerDocSpec.groovy, spock-specs/src/test/groovy/org/spockframework/mock/runtime/ByteBuddyMockMakerSpec.groovy, spock-specs/src/test/groovy/org/spockframework/mock/runtime/CglibMockMakerSpec.groovy, spock-specs/src/test/groovy/org/spockframework/mock/runtime/JavaProxyMockMakerSpec.groovy, spock-specs/src/test/groovy/org/spockframework/mock/runtime/MockMakerRegistrySpec.groovy, spock-specs/src/test/groovy/org/spockframework/mock/runtime/mockito/MockitoMockMakerSpec.groovy
I had a half-finished review of PR #1753, then got a bad cold.
Now you merged it already, so I moved my review comments into this PR here.
Most changes are just minor.
One notable change is, that I changed the order of cglib and mockito.
Even though cglib is deprecated, I think it should sill be selected before mockito for consistency.
If you currently have cglib on the classpath but no byte buddy, it will be used,
then with the new version suddenly mockito will be used which could change the behavior.
It swapped the order, so that mockito is below, so that it is just used as fallback for cases that couldn't be handled before.
What do you think?
Another notable change is, that I changed the toString of the mock maker settings implementations that just returned the
mock maker id before and …
=> Some improvements for the work from PR #1753

spock-core/src/main/java/org/spockframework/lang/SpecInternals.java
With this information tools and code operating after semantic analysis phase where Spock
made its transformations have some additional type information. For example @CompileStatic
or @TypeChecked can now see some more types.
=> Add some type information to SpecInternals

spock-core/src/main/java/org/spockframework/runtime/RunContext.java
Now the initialization of the MockMakerRegistry in RunContext is only done, when getMockMakerRegistry() is called.
This should speed up the execution of EmbeddedSpecs, when they do not use mocks.
=> Make MockMakerRegistry initialization lazy

docs/interaction_based_testing.adoc, docs/parallel_execution.adoc, docs/release_notes.adoc, spock-core/src/main/java/org/spockframework/mock/runtime/GroovyMockFactory.java, spock-specs/src/test/groovy/org/spockframework/docs/interaction/GlobalMockDocSpec.groovy, spock-specs/src/test/groovy/org/spockframework/smoke/mock/GroovyMockGlobalClass.groovy, spock-specs/src/test/groovy/org/spockframework/smoke/mock/GroovyMocks.groovy
- Add check to prevent double global mocking
- Use local class for test to avoid cross contamination
- Update documentation
=> Make Groovy global mocking more strict

docs/extensions.adoc, docs/release_notes.adoc, spock-core/src/main/java/org/spockframework/runtime/extension/builtin/TempDirExtension.java, spock-core/src/main/java/org/spockframework/runtime/extension/builtin/TempDirInterceptor.java, spock-core/src/main/java/org/spockframework/util/IThrowableBiConsumer.java, spock-core/src/main/java/spock/lang/TempDir.java, spock-specs/src/test/groovy/org/spockframework/docs/extension/TempDirDocSpec.groovy, spock-specs/src/test/groovy/org/spockframework/smoke/extension/TempDirExtensionSpec.groovy
* Enable parameter injection for @TempDir.
* Prior to this commit @TempDir values where not available to other field initializers,
now they can be used to initialize other fields.
* Fixed exception when configured baseDir was not existing,
now @TempDir will create the baseDir directory if it is missing.
=> Enable parameter injection for @TempDir and run as initialization interceptor for fields

.github/renovate.json5
With a suggestion from:
https://github.com/renovatebot/renovate/discussions/27303#discussioncomment-8473222
I will handle Groovy version handling separately, once Mockito is confirmed.
Fixes problem reported in https://github.com/spockframework/spock/pull/1871#issuecomment-1915675914.
=> Fix preserving Mockito 4.x version by Renovate

.github/renovate.json5
Renovate has recently started supporting Gradle version catalog natively, so regex manager no longer handles that (see #1883).
This change implements the same logic (preserve major Groovy version for our variables) in a native way. Additionally, the simplified JSON5 syntax is applied and `config:recommended` is used after [changes in Renovate 36](https://docs.renovatebot.com/release-notes-for-major-versions/#version-36).
=> [Renovate] Improve Groovy versions handling + minor tweaks

docs/release_notes.adoc, spock-core/src/main/java/org/spockframework/mock/runtime/ByteBuddyMockMaker.java, spock-core/src/main/java/org/spockframework/mock/runtime/CglibMockMaker.java, spock-core/src/main/java/org/spockframework/mock/runtime/JavaProxyMockMaker.java, spock-core/src/main/java/org/spockframework/util/ReflectionUtil.java, spock-specs/src/test/groovy/org/spockframework/mock/runtime/ByteBuddyMockMakerSpec.groovy, spock-specs/src/test/groovy/org/spockframework/mock/runtime/ByteBuddyTestClassLoader.java, spock-specs/src/test/groovy/org/spockframework/mock/runtime/JavaProxyMockMakerSpec.groovy, spock-specs/src/test/groovy/org/spockframework/mock/runtime/mockito/MockitoMockMakerSpec.groovy, spock-specs/src/test/groovy/org/spockframework/util/ReflectionUtilSpec.groovy
Now it is supported to mock classes and interfaces from different classloaders with the mockito mock maker.
The mock makers java-proxy, byte-buddy and cglib do not support that mode.
Previously the mocking failed, because the java-proxy and byte-budy mock maker would ave tried to load the different classes, 
but these would not be visible, if one if ther class or interface were not visible to the classloader used by the mock.
=> Support mocking of classes from different classloaders

docs/release_notes.adoc, spock-core/src/main/java/org/spockframework/mock/runtime/GroovyMockFactory.java, spock-specs/src/test/groovy/org/spockframework/smoke/mock/GroovyMockAbstractGlobalClass.groovy, spock-specs/src/test/groovy/org/spockframework/smoke/mock/GroovyMockFinalClass.groovy, spock-specs/src/test/groovy/org/spockframework/smoke/mock/GroovyMocksForInterfaces.groovy
This allows the GroovyMockFactory to spin a new subclass, if the global mock is an abstract class.
This fixes #464
=> Support creation of global mocks for abstract classes

docs/release_notes.adoc, spock-core/src/main/java/org/spockframework/mock/runtime/MockController.java, spock-core/src/main/java/org/spockframework/mock/runtime/MockInteraction.java, spock-specs/src/test/groovy/org/spockframework/smoke/mock/MultiThreaded.groovy
Prior to this commit the response handler of a mock was called in a
synchronized method. This could lead to deadlocks when one mock was
blocking in its response handler to wait on another mock.
fixes #583, #1882
=> Execute Mock response handlers un-synchronized

spock-core/src/main/java/org/spockframework/runtime/extension/builtin/UseExtension.java, spock-specs/src/test/groovy/spock/util/mop/UseSpec.groovy
For `@Use` on a specification same-thread policy is necessary as the whole
spec execution is wrapped in a use-closure, so that also helper methods
can use the category methods.
For `@Use` on features or fixture method this is not necessary, as just the method invocation
is wrapped in the use-closure and this is then always run within one thread.
=> Make `@Use` on feature and fixture method parallel

docs/release_notes.adoc
`-` seems to be used instead of `_`, resulting in 404.
Probably, it would be good to "somehow" fix also published documentation for 2.4-M2.
=> Fix links in release notes for 2.4-M2

spock-core/src/main/java/org/spockframework/runtime/extension/builtin/RepeatUntilFailureExtension.java, spock-specs/src/test/groovy/org/spockframework/smoke/extension/RepeatUntilFailureExtensionSpec.groovy
Currently if you do that, both skip the other one.
But sometimes you want to repeat multiple features in a specification,
especially when trying to reprodocue flaky race-conditon tests.
=> Allow multiple @RepeatUntilFailure annotations within the same specification

build-logic/asciidoc-extensions/src/main/java/org/spockframework/plugins/asciidoctor/IncludedSourceLinker.java, build-logic/asciidoc-extensions/src/main/java/org/spockframework/plugins/asciidoctor/SpockExtension.java, build-logic/asciidoc-extensions/src/main/java/org/spockframework/plugins/asciidoctor/SpockIssueInlineMacroProcessor.java, build-logic/asciidoc-extensions/src/main/java/org/spockframework/plugins/asciidoctor/SpockPullInlineMacroProcessor.java, build-logic/asciidoc-extensions/src/main/resources/META-INF/services/org.asciidoctor.jruby.extension.spi.ExtensionRegistry, build.gradle, docs/docinfo.html, docs/include.adoc
Will look like this when produced:
And additionally logs warnings for listing blocks that do not have a source include like
> WARNUNG: listing with only inline code found; if this is not source from a file, consider using a literal block instead; first line: foo.bar() >> { throw new IOException() } >>> [1, 2, 3] >> { throw new RuntimeException() }
=> Automatically link source snippets in the documentation to the code

.github/actions/setup-jdks/action.yml
By switching to Zulu - Temurin JDK 8 is not available for ARM - https://github.com/adoptium/adoptium/issues/96
It could be done more subtle, but changing the distro only for MacOS builds with JDK 8, if preferred.
=> Fix JDK 8 build on GH Actions with macos 14

docs/release_notes.adoc, spock-core/src/main/java/org/spockframework/mock/constraint/TypeArgumentConstraint.java, spock-core/src/main/java/org/spockframework/util/ReflectionUtil.java, spock-specs/src/test/groovy/org/spockframework/mock/response/MockPrimitiveTypeResponsesSpec.groovy
Now the TypeArgumentConstraint also is satisfied when a type is a primitive type and the passed arg is a wrapper instance of that primitive type.
Fixes #1974
=> TypeArgumentConstraint handles primitive types constraints

spock-core/core.gradle
Allows the usage of Mockito 5 in OSGi environment.
This changes the version range from `[4.11,5)` to `[4.11,6)` for the Mockito import packages.
=> Mockito 5 usage in OSGi env

docs/release_notes.adoc, spock-core/src/main/groovy/spock/util/EmbeddedSpecCompiler.groovy, spock-core/src/main/groovy/spock/util/EmbeddedSpecRunner.groovy, spock-specs/src/test/groovy/spock/util/EmbeddedSpecRunnerClassLoaderSpec.groovy
EmbeddedSpecRunner and EmbeddedSpecCompiler now support the construction with a ClassLoader. 
This allows the use of these classes in an OSGi environment, where the class imports in the embedded spec are not visible by the Spock OSGi bundle ClassLoader
=> EmbeddedSpecRunner/Compiler ClassLoader support

build-logic/settings.gradle, build.gradle, spock-core/core.gradle, spock-specs/mock-integration/mock-integration.gradle, spock-specs/specs.gradle, spock-testkit/testkit.gradle
This PR fixes some trivial Gradle deprecations.
Imo, there is potential for further work in the Gradle Build of Spock like removing other deprecations or getting ready for configuration cache. But for now, this is a nice and simple fix for some of the deprecations.
=> Fix trivial Gradle deprecations

docs/release_notes.adoc, spock-core/src/main/java/org/spockframework/mock/runtime/ByteBuddyMockFactory.java, spock-specs/src/test/groovy/org/spockframework/mock/runtime/ByteBuddyMockMakerSpec.groovy, spock-specs/src/test/groovy/org/spockframework/mock/runtime/ByteBuddyTestClassLoader.java
ByteBuddy: Do not use Lookup for non-local mocks
This PR introduces the concept of local mocks. A mock is considered to be local if the target class' classloader can also load all additional interfaces (incl. `ISpockMockObject`).
The lookup classloading strategy may only be used if a mock is local.
Otherwise we have to defer to other strategies.
Fixes #2017
=> ByteBuddy: Do not use Lookup for non-local mocks

docs/data_driven_testing.adoc, docs/release_notes.adoc, spock-specs/src/test/groovy/org/spockframework/datapipes/DataPipesIteratorSpec.groovy
Added note to the documentation to clarify the usage of Iterables
as data pipes and the used size() method.
Fixes #2022
=> Clarified documentation about Iterable data providers and size() calls 

docs/release_notes.adoc, spock-core/src/main/java/org/spockframework/compiler/AbstractDeepBlockRewriter.java, spock-specs/src/test-groovy-ge-4.0/groovy/org/spockframework/smoke/condition/ConditionG4Spec.groovy
=> Fix compile error with single explicit assert in switch expression branch (#1845)

build-logic/preprocess-workflows/preprocess-workflows.gradle, build-logic/preprocess-workflows/src/main/groovy/org/spockframework/gradle/PreprocessWorkflowsPlugin.groovy, build.gradle, gradle/libs.versions.toml
This contains old Kotlin version to test that Renovate now properly updates it.
=> Move workflows Kotlin dependencies for Gradle to version catalog

docs/release_notes.adoc, spock-core/src/main/java/org/spockframework/runtime/ExtensionClassesLoader.java, spock-core/src/main/java/org/spockframework/util/ReflectionUtil.java, spock-specs/src/test/groovy/org/spockframework/util/ReflectionUtilSpec.groovy
Implement the same resource logic with ContextClassLoader as JUnit platform.
Fixes #2076
=> Fix ExtensionException in OSGi environment for global extension

build.gradle, gradle/publishMaven.gradle, spock-bom/bom.gradle
=> Publish module-alignment metadata (#2075)

.github/renovate.json5
It should prevent 2.3-groovy-3.0 -> 2.3-groovy-4.0 upgrade by Renovate, such as: https://github.com/spockframework/spock/pull/2098
=> Prevent major Groovy version upgrade for Spock dependency in tests
