spockframework/spock

- CONTRIBUTING.md
As per issue #70 IntelliJ gradle import fails
> Updated docs to reflect current IntelliJ project generation approach

- spock-specs/specs.gradle
also fixed issue with jitpack-io provided snapshot build thanks to @jitpack-io
> Use new SNAPSHOT of cglib which uses Opcodes.ASM5 instead of ASM4

- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/TimeoutInterceptor.java
Use CoundDownLatch to start the timeout watch thread and the feature invocation at the same time
> CoundDownLatch for TimeoutInterceptor

- docs/extensions.adoc
The original https://github.com/spockframework/spock/pull/51 change got somehow lost
> @ConfineMetaClassChanges requires a list of classes as value

- docs/all_in_one.adoc
- docs/data_driven_testing.adoc
- docs/extensions.adoc
- docs/getting_started.adoc
- docs/interaction_based_testing.adoc
- docs/introduction.adoc
- docs/migration_guide.adoc
- docs/modules.adoc
- docs/release_notes.adoc
- docs/spock_primer.adoc
Use Asciidoctors leveloffset attribute when including the sections into the all in one doc
> Use Asciidoctors leveloffset attribute for all-in-one doc

- docs/extensions.adoc
- spock-core/src/main/java/org/spockframework/report/log/ReportLogConfiguration.java
- spock-specs/src/test/groovy/org/spockframework/report/log/ReportLogConfigurationSpec.groovy
Fix for bug in ReportLogConfiguration
Thanks @wojciszek for reporting:
https://github.com/spockframework/spock/commit/542f57474e528d19100d4685f0d3f6eb8891f698#commitcomment-11595886
> Fix handling of spock.logEnabled system property

- docs/extensions.adoc
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/PendingFeatureExtension.java
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/PendingFeatureInterceptor.java
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/PendingFeatureIterationInterceptor.java
- spock-core/src/main/java/spock/lang/PendingFeature.java
- spock-specs/src/test/groovy/org/spockframework/smoke/extension/PendingFeatureExtensionSpec.groovy
Add @PendingFeature since Groovy's @NotYetImplemented AST transform has some caveats with data driven tests
See also Issue #84
> Add @PendingFeature

- .idea/codeStyleSettings.xml
- .idea/copyright/profiles_settings.xml
- spock-core/src/main/java/org/spockframework/lang/SpecInternals.java
- spock-core/src/main/java/org/spockframework/report/log/ReportLogExtension.java
- spock-core/src/main/java/org/spockframework/runtime/BaseSpecRunner.java
- spock-core/src/main/java/org/spockframework/runtime/IRunSupervisor.java
- spock-core/src/main/java/org/spockframework/runtime/JUnitSupervisor.java
- spock-core/src/main/java/org/spockframework/runtime/ParameterizedSpecRunner.java
- spock-core/src/main/java/org/spockframework/runtime/RunContext.java
- spock-core/src/main/java/org/spockframework/runtime/SafeIterationNameProvider.java
- spock-core/src/main/java/org/spockframework/runtime/Scheduler.java
- spock-core/src/main/java/org/spockframework/runtime/SequentialRunnerScheduler.java
- spock-core/src/main/java/org/spockframework/runtime/Sputnik.java
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/ConcurrentExecutionModeExtension.java
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/StepwiseExtension.java
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/UnrollNameProvider.java
- spock-core/src/main/java/org/spockframework/runtime/model/FeatureInfo.java
- spock-core/src/main/java/org/spockframework/runtime/model/SpecInfo.java
- spock-core/src/main/java/spock/lang/ConcurrentExecutionMode.java
- spock-core/src/test/java/org/spockframework/runtime/SchedulerTest.java
- spock-specs/src/test/groovy/org/spockframework/junit/scheduling/SchedulingTest.groovy
- spock-specs/src/test/groovy/org/spockframework/runtime/ClosingOfDataProviders.groovy
- spock-specs/src/test/groovy/org/spockframework/runtime/EstimatedNumberOfIterations.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/parameterization/UnrolledFeatureMethods.groovy
JUnit supports parallel execution of test methods: Runner should extends ParentRunner and utilize RunnerScheduler to execute tests.
> Support for parallel execution of features and iterations

- build.gradle
- spock-specs/specs.gradle
This replaces the need for the jitpack ad-hoc snapshot build.
> Update to cglib 3.2.0

- docs/interaction_based_testing.adoc
As it was released some time ago: https://github.com/cglib/cglib/releases/tag/RELEASE_3_2_0
> Update information about CGLIB 3.2.0 availability

- spock-core/src/main/java/org/spockframework/compiler/AstNodeCache.java
- spock-core/src/main/java/org/spockframework/compiler/ConditionRewriter.java
- spock-core/src/main/java/org/spockframework/runtime/Condition.java
- spock-core/src/main/java/org/spockframework/runtime/ConditionNotSatisfiedError.java
- spock-core/src/main/java/org/spockframework/runtime/ExpressionInfoBuilder.java
- spock-core/src/main/java/org/spockframework/runtime/InvalidSpecException.java
- spock-core/src/main/java/org/spockframework/runtime/JUnitSupervisor.java
- spock-core/src/main/java/org/spockframework/runtime/SpockException.java
- spock-core/src/main/java/org/spockframework/runtime/SpockExecutionException.java
- spock-core/src/main/java/org/spockframework/runtime/SpockRuntime.java
- spock-core/src/main/java/org/spockframework/runtime/ValueRecorder.java
- spock-core/src/main/java/org/spockframework/runtime/extension/ExtensionException.java
- spock-core/src/main/java/org/spockframework/runtime/model/ExpressionInfo.java
- spock-core/src/main/java/org/spockframework/util/IncompatibleGroovyVersionException.java
- spock-core/src/main/java/org/spockframework/util/WrappedException.java
- spock-specs/src/test/groovy/org/spockframework/smoke/condition/ExceptionsInConditions.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/condition/MatcherConditions.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/extension/ReportLogExtensionSpec.groovy
This pull request is copy of #49 but rebased on master.
Please post any questions/feedbacks to #49 to keep all in one place.
> render exceptions in conditions as condition failure (copy of #49)

- spock-core/src/main/java/org/spockframework/compiler/AbstractDeepBlockRewriter.java
- spock-core/src/main/java/org/spockframework/compiler/AstNodeCache.java
- spock-core/src/main/java/org/spockframework/compiler/ConditionRewriter.java
- spock-core/src/main/java/org/spockframework/compiler/DeepBlockRewriter.java
- spock-core/src/main/java/org/spockframework/compiler/IRewriteResources.java
- spock-core/src/main/java/org/spockframework/compiler/ISpecialMethodCall.java
- spock-core/src/main/java/org/spockframework/compiler/NoSpecialMethodCall.java
- spock-core/src/main/java/org/spockframework/compiler/SpecRewriter.java
- spock-core/src/main/java/org/spockframework/compiler/SpecialMethodCall.java
- spock-core/src/main/java/org/spockframework/runtime/ErrorCollector.java
- spock-core/src/main/java/org/spockframework/runtime/JUnitSupervisor.java
- spock-core/src/main/java/org/spockframework/runtime/SpockRuntime.java
- spock-core/src/main/java/org/spockframework/util/Identifiers.java
- spock-core/src/main/java/spock/lang/Specification.java
- spock-core/src/main/java/spock/util/concurrent/PollingConditions.java
- spock-specs/src/test/groovy/org/spockframework/verifyall/VerifyAllSpecification.groovy
A rebased version of https://github.com/spockframework/spock/pull/557
> Specification.verifyAll aka block/soft asserts

- build.gradle
As my previous PR got forked and merged in an outdated state, I propose raising library versions to the ones up to date right now.
> update external dependencies (2)

- README.md
- build.gradle
> Changing default variant to 2.4

- README.md
- build.gradle
- spock-core/src/main/java/org/spockframework/runtime/ExpressionInfoBuilder.java
- spock-specs/src/test/groovy/org/spockframework/smoke/condition/ConditionEvaluation.groovy
Third try. this time it looks right.
> rendering if condition (after removing line breaks) can not be parsed (Was #550)

- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/IssueExtension.java
- spock-specs/src/test/groovy/org/spockframework/smoke/extension/IssueExtension.groovy
> Support https protocol and multiple values in IssueExtension class.

- build.gradle
- docs/all_in_one.adoc
- docs/data_driven_testing.adoc
- docs/extensions.adoc
- docs/getting_started.adoc
- docs/include.adoc
- docs/index.adoc
- docs/interaction_based_testing.adoc
- docs/introduction.adoc
- docs/migration_guide.adoc
- docs/modules.adoc
- docs/release_notes.adoc
- docs/spock_primer.adoc
- spock-specs/src/test/groovy/org/spockframework/docs/datadriven/DataSpec.groovy
- spock-specs/src/test/groovy/org/spockframework/docs/datadriven/v1/MathSpec.groovy
- spock-specs/src/test/groovy/org/spockframework/docs/datadriven/v2/MathSpec.groovy
- spock-specs/src/test/groovy/org/spockframework/docs/datadriven/v3/MathSpec.groovy
- spock-specs/src/test/groovy/org/spockframework/docs/datadriven/v4/MathSpec.groovy
- spock-specs/src/test/groovy/org/spockframework/docs/datadriven/v5/MathSpec.groovy
- spock-specs/src/test/groovy/org/spockframework/docs/interaction/InteractionDocSpec.groovy
Move code from docs into real specs and use includes
to integrate them into the generated documentation.
> Refactor docs to have tested examples

- build.gradle
- settings.gradle
- spock-bom/bom.gradle
The spock-bom project generates a Maven compatible bill of materials
pom.xml which manages all spock artifacts.
> Add spock-bom project

- README.md
- build.gradle
Change from 1.1-groovy-2.4-rc-1 to 1.1-rc-1-groovy-2.4
or 1.1-groovy-2.4-SNAPSHOT to 1.1-SNAPSHOT-groovy-2.4
> Change version scheme to have variant at the end

- spock-core/src/main/java/org/spockframework/runtime/ExtensionClassesLoader.java
Implement #674 with fail fast and helpful Exception information
> Prevent multiple addition of a global extension

- build.gradle
Please issue https://github.com/spockframework/spock/issues/806 for more information.
> Generate anchor for sections to easier link creation and reference

- spock-core/src/main/java/org/spockframework/runtime/ValueRecorder.java
Exception message had incorrect grammar.
> Reword ValueRecorder exception message

- spock-core/src/main/java/org/spockframework/compiler/AstNodeCache.java
- spock-core/src/main/java/org/spockframework/compiler/ConditionRewriter.java
- spock-core/src/main/java/org/spockframework/compiler/DeepBlockRewriter.java
- spock-core/src/main/java/org/spockframework/compiler/RecorderScopeNameRewriter.java
- spock-core/src/main/java/org/spockframework/runtime/SpockRuntime.java
- spock-specs/src/test/groovy/org/spockframework/smoke/WithBlockFailingConditions.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/WithBlockPassingConditions.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/WithBlocks.groovy
- spock-specs/src/test/groovy/org/spockframework/verifyall/VerifyAllSpecification.groovy
>  Improve handling of nested with and verify all... 

- docs/release_notes.adoc
- spock-core/src/main/java/org/spockframework/mock/runtime/InteractionScope.java
- spock-core/src/main/java/org/spockframework/util/ExceptionUtil.java
- spock-specs/src/test/groovy/org/spockframework/smoke/mock/OrderedInteractions.groovy
> Fix assertion of mock invocation order with nested invocations (#475)

- docs/extensions.adoc
- docs/release_notes.adoc
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/RetryExtension.java
- spock-core/src/main/java/spock/lang/Retry.java
- spock-specs/src/test/groovy/org/spockframework/smoke/extension/RetryFeatureExtensionSpec.groovy
Implementation of option (2) for #874.
> Make Retry annotation declarable on spec classes

- spock-spring/src/main/java/org/spockframework/spring/ScanScopedBeans.java
- spock-spring/src/main/java/org/spockframework/spring/SpringBean.java
- spock-spring/src/main/java/org/spockframework/spring/SpringSpy.java
- spock-spring/src/main/java/org/spockframework/spring/StubBeans.java
- spock-spring/src/main/java/org/spockframework/spring/UnwrapAopProxy.java
Just in a case there will be needed to change it in a not backward
compatible way.
> Mark new Spring extensions as @Beta

- spock-core/src/main/java/org/spockframework/compiler/InteractionRewriter.java
- spock-core/src/main/java/org/spockframework/mock/constraint/NamedArgumentListConstraint.java
- spock-core/src/main/java/org/spockframework/mock/constraint/PositionalArgumentListConstraint.java
- spock-core/src/main/java/org/spockframework/mock/runtime/InteractionBuilder.java
- spock-specs/src/test/groovy/org/spockframework/smoke/mock/ArgumentMatching.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/mock/TooFewInvocations.groovy
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/919)
> Add support for mixed named and positional arguments in mocks

- build.gradle
- spock-core/core.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/927)
> Update to ByteBuddy 1.9.1

- spock-core/src/main/java/org/spockframework/runtime/ExpressionComparisonRenderer.java
- spock-core/src/main/java/org/spockframework/runtime/ExpressionInfoValueRenderer.java
- spock-core/src/main/java/org/spockframework/runtime/FailedEqualityComparisonRenderer.java
- spock-core/src/main/java/org/spockframework/runtime/FailedInstanceOfComparisonRenderer.java
- spock-core/src/main/java/org/spockframework/runtime/FailedSetEqualityComparisonRenderer.java
- spock-core/src/main/java/org/spockframework/runtime/FailedStringComparisonRenderer.java
- spock-specs/src/test/groovy/org/spockframework/smoke/condition/ConditionRenderingSpec.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/condition/SetComparisonRendering.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/condition/StringComparisonRendering.groovy
fixes #924
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/925)
> Add special rendering for Set comparisons

- .circleci/config.yml
- README.md
- build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/929)
> Update to CircleCi 2.0

- spock-core/src/main/java/org/spockframework/runtime/RunContext.java
- spock-core/src/main/java/org/spockframework/runtime/condition/DiffedClassRenderer.java
- spock-specs/src/test/groovy/org/spockframework/smoke/condition/DiffedObjectRendering.groovy
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/932)
> Render class loader for classes in comparison failures

- spock-core/src/main/java/org/spockframework/compiler/ConditionRewriter.java
- spock-core/src/main/java/org/spockframework/runtime/ExpressionInfoConverter.java
- spock-core/src/main/java/org/spockframework/runtime/ValueRecorder.java
- spock-specs/src/test/groovy/org/spockframework/smoke/condition/ConditionRendering.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/condition/EqualityComparisonRendering.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/condition/StringComparisonRendering.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/condition/ValueRendering.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/mock/TooFewInvocations.groovy
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/935)
> Record class literal values and display them in comparison failures to see FQCN

- docs/release_notes.adoc
- spock-core/src/main/java/org/spockframework/compiler/ConditionRewriter.java
- spock-specs/src/test/groovy/org/spockframework/smoke/condition/ConditionRendering.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/condition/ExplicitConditionsWithMessage.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/condition/MatcherConditionRendering.groovy
fixes #922
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/928)
> Add power assertion output to asserts with explicit message

- spock-core/src/main/java/org/spockframework/util/AbstractExpressionConverter.java
- spock-specs/src/test/groovy/org/spockframework/smoke/condition/ConditionRendering.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/condition/ConditionRenderingSpec.groovy
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/930)
> Do not convert implicit "this" expression like when calling the constructor of a non-static inner class

- spock-core/src/main/java/org/spockframework/compiler/ConditionRewriter.java
- spock-specs/src/test/groovy/org/spockframework/smoke/condition/ConditionRendering.groovy
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/937)
> Fix class expression recording when there are comments with dots in the same line

- spock-core/src/main/java/org/spockframework/runtime/ExpressionInfoValueRenderer.java
- spock-specs/src/test/groovy/org/spockframework/smoke/condition/ExceptionsInConditions.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/extension/ReportLogExtensionSpec.groovy
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/938)
> Show stacktrace of throwables in comparison failure result

- spock-core/src/main/java/org/spockframework/runtime/ExpressionInfoValueRenderer.java
- spock-core/src/main/java/org/spockframework/runtime/FailedEqualityComparisonRenderer.java
- spock-specs/src/test/groovy/org/spockframework/smoke/condition/EqualityComparisonRendering.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/condition/ValueRendering.groovy
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/936)
> Render irrelevant expressions if they get a type hint in comparison failure

- .travis.yml
- build.gradle
- spock-spring/boot2-test/boot2-test.gradle
Unfortunately, the build fails because of: https://issues.apache.org/jira/browse/GROOVY-8727
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/900)
> Add JDK 11 to Travis

- docs/release_notes.adoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/940)
> Add release notes for my merged PRs

- spock-core/src/main/resources/org/spockframework/idea/spock.gdsl
fixes #954
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/955)
> Fix NPE in spock.gdsl

- spock-core/src/main/java/org/spockframework/runtime/ExpressionInfoValueRenderer.java
- spock-specs/src/test/groovy/org/spockframework/smoke/StackTraceFiltering.groovy
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/944)
> Filter stack traces when rendered in expression info value renderer

- spock-core/src/main/java/spock/mock/MockingApi.java
- spock-core/src/main/java/spock/util/concurrent/AsyncConditions.java
- spock-core/src/main/java/spock/util/concurrent/BlockingVariable.java
Hi,
i fixed the javadoc issues regarding the wrong arrow syntax.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1045)
> Fixes #1018 wrong java doc

- docs/interaction_based_testing.adoc
Fixes #1033 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1034)
> Fix senseless interaction example

- docs/all_in_one.adoc
- docs/index.adoc
- docs/known_issues.adoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1072)
> Add Known Issues Section to docs

- spock-core/src/main/java/org/spockframework/lang/SpecInternals.java
- spock-specs/src/test/groovy/org/spockframework/smoke/mock/JavaSpies.groovy
Fixes #1029
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1074)
> Forbid spying on Spies

- spock-core/src/main/java/org/spockframework/mock/constraint/TargetConstraint.java
- spock-specs/src/test/groovy/org/spockframework/smoke/mock/InvalidStubInteraction.groovy
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1086)
> Fail-fast for invalid Stub interactions

- spock-core/src/main/java/org/spockframework/mock/runtime/MockInstantiator.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1021)
> Do not append "null" to a CannotCreateMockException

- docs/extensions.adoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1083)
> fix typo on extensions doc

- spock-core/src/main/java/org/spockframework/mock/EmptyOrDummyResponse.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1091)
> Remove unnecessary reflection for Java 8 types in EmptyOrDummyResponse

- spock-core/src/main/java/org/spockframework/mock/EmptyOrDummyResponse.java
- spock-specs/src/test/groovy/org/spockframework/smoke/mock/StubBuilderSupport.groovy
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1092)
> Fix EmptyOrDummyResponse returning mock instance for Object

- docs/interaction_based_testing.adoc
- docs/release_notes.adoc
- spock-core/src/main/java/org/spockframework/mock/response/WildcardResponseGenerator.java
- spock-specs/src/test/groovy/org/spockframework/smoke/mock/ChainedResponseGenerators.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/mock/JavaSpies.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/mock/MockBasics.groovy
fixes #1035
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1090)
> Change >>_ from default response to stub response

- spock-core/src/main/java/org/spockframework/mock/WrongInvocationOrderError.java
- spock-core/src/main/java/org/spockframework/mock/runtime/InteractionScope.java
- spock-specs/src/test/groovy/org/spockframework/smoke/mock/OrderedInteractions.groovy
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1093)
> Print up to 5 last mock invocations for a wrong oder error

- spock-core/src/main/java/org/spockframework/lang/SpecInternals.java
- spock-core/src/main/java/spock/mock/MockingApi.java
- spock-specs/src/test/groovy/org/spockframework/smoke/mock/JavaSpies.groovy
Fixes #1028
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1115)
> Add Spy(T obj, Closure interactions) (#1028)

- build.gradle
- docs/data_driven_testing.adoc
- docs/extensions.adoc
- docs/interaction_based_testing.adoc
- docs/migration_guide.adoc
- docs/release_notes.adoc
- docs/spock_primer.adoc
Fixes #1037
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1122)
> Fix dead cross-page links on one-page variant (#1037)

- spock-core/src/main/java/org/spockframework/compiler/DeepBlockRewriter.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1131)
> Simplify work-around to get the reference to the current closure

- docs/release_notes.adoc
- spock-core/src/main/java/org/spockframework/compiler/InteractionRewriter.java
- spock-core/src/main/java/spock/mock/MockingApi.java
- spock-specs/src/test/groovy/org/spockframework/smoke/mock/InteractionsWithPropertySyntax.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/mock/JavaSpies.groovy
Fixes #1040
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1121)
> Support property getter stubbing without it (#1040)

- docs/data_driven_testing.adoc
- docs/release_notes.adoc
- spock-core/src/main/java/org/spockframework/compiler/AstUtil.java
- spock-core/src/main/java/org/spockframework/compiler/WhereBlockRewriter.java
- spock-specs/src/test/groovy/org/spockframework/docs/datadriven/DataSpec.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/parameterization/DataTables.groovy
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1113)
> Support two or more underscores to separate multiple data tables

- docs/release_notes.adoc
- spock-core/src/main/java/org/spockframework/compiler/ConditionRewriter.java
- spock-specs/src/test/groovy/org/spockframework/smoke/DisambiguationInConditions.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/DisambiguationInConditionsTestee.java
Fixes #1022
Fixes #589
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1124)
> Carry over type casts in rewritten conditions to not disturb method disambiguation (#1022)

- docs/data_driven_testing.adoc
- docs/release_notes.adoc
- spock-core/src/main/java/org/spockframework/compiler/WhereBlockRewriter.java
- spock-specs/src/test/groovy/org/spockframework/docs/datadriven/v6/MathSpec.groovy
- spock-specs/src/test/groovy/org/spockframework/docs/datadriven/v7/MathSpec.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/parameterization/DataTables.groovy
closes #1024
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1130)
> Support semicolons as data table column separator (#1024)

- docs/data_driven_testing.adoc
- docs/migration_guide.adoc
- docs/release_notes.adoc
- spock-core/src/main/java/org/spockframework/runtime/DataVariablesIterationNameProvider.java
- spock-core/src/main/java/org/spockframework/runtime/PlatformParameterizedSpecRunner.java
- spock-core/src/main/java/org/spockframework/runtime/PlatformSpecRunner.java
- spock-core/src/main/java/org/spockframework/runtime/SafeIterationNameProvider.java
- spock-core/src/main/java/org/spockframework/runtime/SpockEngineDiscoveryPostProcessor.java
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/UnrollExtension.java
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/UnrollIterationNameProvider.java
- spock-core/src/main/java/org/spockframework/runtime/model/IterationInfo.java
- spock-core/src/main/java/org/spockframework/util/DataVariableMap.java
- spock-junit4/src/test/groovy/org/spockframework/junit4/junit/UseJUnitTestNameRule.groovy
- spock-specs/src/test/groovy/org/spockframework/docs/datadriven/DataSpec.groovy
- spock-specs/src/test/groovy/org/spockframework/runtime/AsyncRunListenerSpec.groovy
- spock-specs/src/test/groovy/org/spockframework/runtime/DataVariablesIterationNameProviderSpec.groovy
- spock-specs/src/test/groovy/org/spockframework/runtime/SafeIterationNameProviderSpec.groovy
- spock-specs/src/test/groovy/org/spockframework/runtime/extension/builtin/UnrollIterationNameProviderSpec.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/parameterization/Parameterizations.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/parameterization/UnrolledFeatureMethods.groovy
- spock-specs/src/test/groovy/org/spockframework/util/DataVariableMapTest.groovy
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1096)
> Change the default unroll pattern to include data variables

- docs/interaction_based_testing.adoc
- docs/release_notes.adoc
- spock-core/src/main/java/org/spockframework/compiler/AbstractDeepBlockRewriter.java
- spock-core/src/main/java/org/spockframework/compiler/AstNodeCache.java
- spock-core/src/main/java/org/spockframework/compiler/DeepBlockRewriter.java
- spock-core/src/main/java/org/spockframework/compiler/SpecialMethodCall.java
- spock-specs/src/test/groovy/org/spockframework/docs/interaction/InteractionDocSpec.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/mock/SpyBasics.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/mock/StubBasics.groovy
Closes #1023
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1123)
> Transport type cast information in constructorArgs to constructor selection (#1023)

- build.gradle
- spock-specs/specs.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1137)
> Fix groovyConsole task and add junit5 runner and ivy to console tasks

- spock-junit4/src/main/java/org/spockframework/junit4/JUnitDescriptionGenerator.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1135)
> Remove IDE specific unnecessary code

- docs/extensions.adoc
- docs/release_notes.adoc
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/IgnoreIfExtension.java
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/PendingFeatureIfExtension.java
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/RequiresExtension.java
- spock-specs/src/test/groovy/org/spockframework/smoke/extension/IgnoreIfExtension.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/extension/RequiresExtension.groovy
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1146)
> Provide the precondition context as argument to the condition closure for easier IDE support

- build.gradle
- spock-unitils/unitils.gradle
As suggested by the versioning plugin.
Some bigger (e.g. Spring-related) left for another PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1151)
> Upgrade Some "minor" dependencies

- docs/release_notes.adoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1147)
> Document a way to use Sputnik dependent things

- spock-core/src/main/java/org/spockframework/mock/runtime/GroovyMockInterceptor.java
- spock-core/src/main/java/org/spockframework/mock/runtime/GroovyMockMetaClass.java
- spock-core/src/main/java/org/spockframework/mock/runtime/JavaMockInterceptor.java
- spock-core/src/main/java/org/spockframework/runtime/GroovyRuntimeUtil.java
- spock-core/src/main/java/org/spockframework/util/ReflectionUtil.java
- spock-core/src/main/java/org/spockframework/util/RenderUtil.java
- spock-specs/src/test/groovy/org/spockframework/smoke/mock/GroovySpiesThatAreGlobal.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/mock/TooManyInvocations.groovy
Fixes #871
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1134)
> Do not strip type information from arguments (#871)

- docs/extensions.adoc
- docs/release_notes.adoc
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/ConditionalExtension.java
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/IgnoreIfExtension.java
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/PendingFeatureIfExtension.java
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/PreconditionContext.java
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/RequiresExtension.java
- spock-core/src/main/java/spock/lang/IgnoreIf.java
- spock-core/src/main/java/spock/lang/PendingFeatureIf.java
- spock-core/src/main/java/spock/lang/Requires.java
- spock-specs/src/test/groovy/org/spockframework/smoke/extension/IgnoreIfExtension.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/extension/PendingFeatureIfExtensionSpec.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/extension/RequiresExtension.groovy
closes #1085
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1094)
> Make data variables available in precondition context (#1085)

- .travis.yml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- settings.gradle
- spock-specs/src/test/groovy/org/spockframework/smoke/condition/ExceptionsInConditions.groovy
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1155)
> Update to gradle 6.3, Add Java 14 to travis

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1156)
> Fix the latest 2.0.x release date in README

- spock-spring/src/test/groovy/org/spockframework/spring/mock/imported/SpringSpyOnTestFieldForExistingGenericBeanIntegrationTests.groovy
- spock-spring/src/test/groovy/org/spockframework/spring/mock/imported/SpringSpyWithAopProxyTests.groovy
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1171)
> Enable Spring tests that used to fail with ByteBuddy

- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/PendingFeatureBaseInterceptor.java
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/PendingFeatureInterceptor.java
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/PendingFeatureIterationInterceptor.java
- spock-specs/src/test/groovy/org/spockframework/smoke/extension/PendingFeatureExtensionSpec.groovy
Again, only last commit to look at for now, rest is just other PRs combined for less conflicts. :-)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1103)
> Fix pending feature logic

- build.gradle
- docs/release_notes.adoc
And along the way also Byte Buddy.
Before the 2.0-M3 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1172)
> Bump Groovy versions

- spock-core/src/main/java/org/spockframework/util/DataVariableMap.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1176)
> Remove assertj in production code

- settings.gradle
- spock-core/core.gradle
Fixes #1174
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1175)
> improve spock's OSGi metadata and add a verification check

- docs/release_notes.adoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1179)
> Prepare M3 Release Notes

- docs/known_issues.adoc
- docs/release_notes.adoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1180)
> Fix documentation

- docs/extensions.adoc
- docs/release_notes.adoc
- spock-core/src/main/groovy/spock/util/EmbeddedSpecRunner.groovy
- spock-core/src/main/java/org/spockframework/runtime/ExtensionClassesLoader.java
- spock-core/src/main/java/org/spockframework/runtime/GlobalExtensionRegistry.java
- spock-core/src/main/java/org/spockframework/runtime/RunContext.java
- spock-core/src/main/java/org/spockframework/runtime/SpecRunHistory.java
- spock-core/src/main/java/org/spockframework/util/IoUtil.java
- spock-core/src/main/resources/META-INF/services/spock.config.ConfigurationObject
- spock-specs/src/test/groovy/org/spockframework/runtime/ExtensionClassesLoaderSpec.groovy
- spock-specs/src/test/groovy/org/spockframework/runtime/GlobalExtensionRegistrySpec.groovy
- spock-specs/src/test/groovy/org/spockframework/runtime/RunContextSpec.groovy
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1183)
> Add a way to register ConfigurationObject globally

- docs/extensions.adoc
- docs/release_notes.adoc
- spock-core/src/main/java/org/spockframework/runtime/ExtensionRunner.java
- spock-core/src/main/java/org/spockframework/runtime/extension/AbstractAnnotationDrivenExtension.java
- spock-core/src/main/java/org/spockframework/runtime/extension/IAnnotationDrivenExtension.java
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/AutoCleanupExtension.java
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/ConditionalExtension.java
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/ConfineMetaClassChangesExtension.java
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/FailsWithExtension.java
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/IgnoreExtension.java
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/IgnoreRestExtension.java
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/IssueExtension.java
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/NarrativeExtension.java
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/PendingFeatureExtension.java
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/RestoreSystemPropertiesExtension.java
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/RetryExtension.java
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/SeeExtension.java
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/StepwiseExtension.java
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/TimeoutExtension.java
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/TitleExtension.java
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/UseExtension.java
- spock-core/src/main/java/spock/mock/AutoAttachExtension.java
- spock-guice/src/main/java/org/spockframework/guice/GuiceExtension.java
- spock-specs/src/test/groovy/org/spockframework/runtime/GlobalExtensionRegistrySpec.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/condition/IsRenderedExtension.groovy
- spock-spring/src/main/java/org/spockframework/spring/UnwrapAopProxyExtension.java
- spock-unitils/src/main/java/org/spockframework/unitils/UnitilsExtension.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1198)
> Enable batch-processing for repeatable annotations

- docs/extensions.adoc
- docs/release_notes.adoc
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/ConfineMetaClassChangesExtension.java
- spock-core/src/main/java/spock/util/mop/ConfineMetaClassChanges.java
- spock-specs/src/test/groovy/org/spockframework/docs/extension/ConfineMetaClassChangesDocSpec.groovy
- spock-specs/src/test/groovy/spock/util/mop/ConfineMetaClassChangesSpec.groovy
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1187)
> Make @ConfineMetaClassChanges repeatable (#1030)

- docs/release_notes.adoc
- spock-core/src/main/java/org/spockframework/compiler/DeepBlockRewriter.java
- spock-specs/src/test/groovy/org/spockframework/smoke/mock/ArgumentMatching.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/mock/TooFewInvocations.groovy
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1205)
>  Fix #994 nested closure in Code argument constraint 

- docs/extensions.adoc
- docs/release_notes.adoc
- spock-core/src/main/java/spock/lang/See.java
- spock-specs/src/test/groovy/org/spockframework/docs/extension/SeeDocSpec.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/extension/SeeExtension.groovy
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1193)
> Make @See repeatable (#1030)

- docs/extensions.adoc
- docs/release_notes.adoc
- spock-core/src/main/java/spock/lang/Subject.java
- spock-specs/src/test/groovy/org/spockframework/docs/extension/SubjectDocSpec.groovy
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1194)
> Make @Subject repeatable (#1030)

- docs/extensions.adoc
- docs/release_notes.adoc
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/UseExtension.java
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/UseInterceptor.java
- spock-core/src/main/java/spock/util/mop/Use.java
- spock-specs/src/test/groovy/org/spockframework/docs/extension/UseDocSpec.groovy
- spock-specs/src/test/groovy/spock/util/mop/UseSpec.groovy
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1195)
> Make @Use repeatable (#1030)

- docs/release_notes.adoc
- spock-guice/src/main/java/org/spockframework/guice/GuiceExtension.java
- spock-guice/src/main/java/spock/guice/UseModules.java
- spock-guice/src/test/groovy/org/spockframework/guice/GuiceMultiAnnotations.groovy
- spock-guice/src/test/groovy/org/spockframework/guice/GuiceMultiModules.groovy
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1196)
> Make @UseModules repeatable (#1030)

- docs/extensions.adoc
- docs/release_notes.adoc
- spock-core/src/main/java/spock/lang/Requires.java
- spock-specs/src/test/groovy/org/spockframework/docs/extension/RequiresDocSpec.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/extension/RequiresExtension.groovy
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1192)
> Make @Requires repeatable (#1030)

- spock-core/src/main/java/org/spockframework/runtime/IterationNode.java
- spock-core/src/main/java/org/spockframework/runtime/ParameterizedFeatureNode.java
- spock-core/src/main/java/org/spockframework/runtime/SpecNode.java
fixes #1169
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1215)
> Check skipped state in Node.prepare and do nothing if already skipped

- spock-core/src/main/java/org/spockframework/mock/runtime/GroovyMockMetaClass.java
- spock-specs/src/test/groovy/org/spockframework/smoke/mock/GroovyMocksForGroovyClasses.groovy
fixes #1216
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1217)
> Perform argument coercion for GroovyMock method arguments

- CONTRIBUTING.md
- README.md
PR fixes some very minor typos.
> Correct minor typos in MarkDown files

- spock-core/src/main/java/org/spockframework/mock/runtime/JavaMockInterceptor.java
- spock-specs/src/test/groovy/org/spockframework/smoke/mock/JavaStubs.groovy
> Fix property handling of groovy abstract classes and interfaces

- docs/extensions.adoc
- docs/release_notes.adoc
- spock-core/src/main/java/spock/lang/IgnoreIf.java
- spock-specs/src/test/groovy/org/spockframework/docs/extension/IgnoreIfDocSpec.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/extension/IgnoreIfExtension.groovy
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1188)
> Make @IgnoreIf repeatable (#1030)

- docs/extensions.adoc
- docs/release_notes.adoc
- spock-core/src/main/java/spock/lang/PendingFeatureIf.java
- spock-specs/src/test/groovy/org/spockframework/docs/extension/PendingFeatureIfDocSpec.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/extension/PendingFeatureIfExtensionSpec.groovy
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/spockframework/spock/1191)
> Make @PendingFeatureIf repeatable (#1030)

- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/TempDirExtension.java
- spock-specs/src/test/groovy/org/spockframework/smoke/extension/TempDirExtensionSpec.groovy
> Fix TempDir not working for inherited fields

- spock-core/src/main/java/org/spockframework/mock/runtime/JavaMockInterceptor.java
- spock-specs/src/test/groovy/org/spockframework/smoke/mock/JavaMocksForGroovyClasses.groovy
> Fix handling of "is" as getter for boolean properties on Mocks

- docs/release_notes.adoc
Related to support for injection into @Shared fields in spock-spring:
https://github.com/spockframework/spock/pull/1255
> Recognize Marcin E. in release notes for 2.0-M5

- docs/data_driven_testing.adoc
- docs/release_notes.adoc
- spock-core/src/main/java/org/spockframework/compiler/WhereBlockRewriter.java
- spock-specs/src/test/groovy/org/spockframework/docs/datadriven/DataSpec.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/parameterization/MethodParameters.groovy
> Cast data variables with type coercion to the declared parameter type (#1279)

- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/TempDirInterceptor.java
- spock-specs/src/test/groovy/org/spockframework/smoke/extension/TempDirExtensionSpec.groovy
> Make TempDirInterceptor safe for parallel invocation of iterations

- spock-core/src/main/java/org/spockframework/runtime/SpecNode.java
- spock-testkit/src/test/groovy/spock/platform/DontSwallowErrorTest.java
- spock-testkit/src/test/groovy/spock/platform/SpockEngineBase.java
- spock-testkit/src/test/groovy/spock/platform/SpockHelloWorldTest.java
- spock-testkit/src/test/groovy/spock/testkit/oom/OomSpec.groovy
> Fix swallowing of unrecoverable Errors

- spock-core/src/main/java/org/spockframework/compiler/ErrorRethrowerUsageDetector.java
- spock-core/src/main/java/org/spockframework/compiler/IRewriteResources.java
- spock-core/src/main/java/org/spockframework/compiler/SpecRewriter.java
- spock-core/src/main/java/org/spockframework/compiler/WhereBlockRewriter.java
- spock-specs/src/test/groovy/org/spockframework/smoke/parameterization/DataProviders.groovy
> Define error rethrower in data provider and processor methods if necessary (#1287)

- spock-core/src/main/java/org/spockframework/runtime/PlatformSpecRunner.java
- spock-core/src/main/java/org/spockframework/runtime/model/MethodInfo.java
- spock-specs/src/test/groovy/org/spockframework/smoke/parameterization/MethodParameters.groovy
> Fix extension-provided method arguments in fixture methods (#1305)

- spock-core/src/main/java/org/spockframework/util/AbstractExpressionConverter.java
> Fix implicit this conversion after bugfix in Groovy (#1318)

- build.gradle
- settings.gradle
byte-buddy and versions plugin. Before the next release.
> Upgrade groovy to 3.0.8 and some other deps

- docs/getting_started.adoc
> Fixing WebConsole link from getting started doc

- docs/extensions.adoc
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/ConditionalExtension.java
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/PreconditionContext.java
- spock-core/src/main/java/spock/lang/Requires.java
- spock-specs/src/test/groovy/org/spockframework/docs/extension/IgnoreIfDocSpec.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/extension/IgnoreIfExtension.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/extension/PendingFeatureIfExtensionSpec.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/extension/RequiresExtension.groovy
> Refactor PreconditionContext to have a dedicated data field for dataVariable access

- docs/extensions.adoc
- spock-specs/src/test/groovy/org/spockframework/docs/extension/IgnoreIfDocSpec.groovy
See https://github.com/spockframework/spock/pull/1362#issuecomment-967220495.
> Document 'reason' for @IgnoreIf

- docs/extensions.adoc
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/IgnoreExtension.java
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/IgnoreIfExtension.java
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/RequiresExtension.java
- spock-core/src/main/java/spock/lang/Ignore.java
- spock-core/src/main/java/spock/lang/IgnoreIf.java
- spock-core/src/main/java/spock/lang/PendingFeatureIf.java
- spock-core/src/main/java/spock/lang/Requires.java
- spock-specs/src/test/groovy/org/spockframework/docs/extension/IgnoreIfDocSpec.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/extension/IgnoreExtension.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/extension/IgnoreIfExtension.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/extension/RequiresExtension.groovy
> Add inheritance support to conditional extensions

- spock-core/src/main/groovy/spock/util/EmbeddedSpecCompiler.groovy
- spock-core/src/main/groovy/spock/util/SourceToAstNodeAndSourceTranspiler.groovy
- spock-specs/src/test/groovy/org/spockframework/runtime/RunListenerSpec.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/FinalFields.groovy
Prior to this commit the imports were added via string concatenation.
> Change EmbeddedSpecCompiler to use ImportCustomizer

- settings.gradle
Update to the latest Bnd Gradle plugin release.
> Update Bnd Gradle plugin to 6.2.0

- .github/actions/setup-jdks/action.yml
- README.adoc
- settings.gradle
- spock-core/src/main/java/org/spockframework/util/ReflectionUtil.java
- spock-spring/boot3-test/boot3-test.gradle
- spock-spring/boot3-test/src/main/java/org/spockframework/boot3/SimpleBootApp.java
- spock-spring/boot3-test/src/main/java/org/spockframework/boot3/jpa/Book.java
- spock-spring/boot3-test/src/main/java/org/spockframework/boot3/jpa/BookRepository.java
- spock-spring/boot3-test/src/main/java/org/spockframework/boot3/service/HelloWorldService.java
- spock-spring/boot3-test/src/main/java/org/spockframework/boot3/service/ScopedHelloWorldService.java
- spock-spring/boot3-test/src/main/java/org/spockframework/boot3/web/HelloWorldController.java
- spock-spring/boot3-test/src/main/resources/application.properties
- spock-spring/boot3-test/src/test/groovy/org/spockframework/boot3/DataJpaTestIntegrationSpec.groovy
- spock-spring/boot3-test/src/test/groovy/org/spockframework/boot3/SimpleBootAppIntegrationSpec.groovy
- spock-spring/boot3-test/src/test/groovy/org/spockframework/boot3/SpringBeanIntegrationSpec.groovy
- spock-spring/boot3-test/src/test/groovy/org/spockframework/boot3/SpringBootTestAnnotationIntegrationSpec.groovy
- spock-spring/boot3-test/src/test/groovy/org/spockframework/boot3/SpringBootTestAnnotationScopedMockSpec.groovy
- spock-spring/boot3-test/src/test/groovy/org/spockframework/boot3/SpringBootTestAnnotationScopedProxyMockSpec.groovy
- spock-spring/boot3-test/src/test/groovy/org/spockframework/boot3/WebMvcTestIntegrationSpec.groovy
- spock-spring/spring6-test/spring6-test.gradle
- spock-spring/src/main/java/org/spockframework/spring/SpringExtension.java
> Fix issues with Spring 6/Spring Boot 3

- spock-core/src/main/java/org/spockframework/runtime/PlatformParameterizedSpecRunner.java
- spock-core/src/main/java/org/spockframework/runtime/extension/IDataDriver.java
- spock-core/src/main/java/org/spockframework/runtime/extension/IIterationRunner.java
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/RepeatUntilFailureExtension.java
- spock-specs/src/test/groovy/org/spockframework/smoke/parameterization/DataProviders.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/parameterization/DataTables.groovy
> Fix regression with estimatedNumIterations always returning -1

- build.gradle
> Fix GroovyDoc issue

- README.adoc
> There is a small typo on readme

- settings.gradle
This PR handles the non yet merged (and outdated):
https://github.com/spockframework/spock/pull/1612
https://github.com/spockframework/spock/pull/1687
> Update Gradle Enterprise plugins

- .github/renovate.json
- .github/renovate.json5
- build.gradle
- gradle/libs.versions.toml
- spock-core/core.gradle
- spock-junit4/junit4.gradle
- spock-specs/specs.gradle
- spock-spring/spring.gradle
- spock-testkit/testkit.gradle
- spock-unitils/unitils.gradle
- Use libs.versions.toml version catalog feature
- Update renovate config to use json5 and ignore...
> Use version catalogs

- docs/extensions.adoc
- gradle/libs.versions.toml
- spock-core/core.gradle
- spock-core/src/main/java/org/spockframework/mock/runtime/mockito/MockitoMockMaker.java
- spock-core/src/main/java/org/spockframework/mock/runtime/mockito/MockitoMockMakerImpl.java
- spock-core/src/main/java/org/spockframework/mock/runtime/mockito/MockitoMockMakerSettings.java
- spock-core/src/main/java/spock/mock/MockMakers.java
- spock-core/src/main/resources/META-INF/services/org.spockframework.mock.runtime.IMockMaker
- spock-specs/mock-integration/mock-integration.gradle
- spock-specs/mock-integration/src/test/groovy/MockingIntegrationSpec.groovy
- spock-specs/specs.gradle
- spock-specs/src/test/groovy/org/spockframework/docs/interaction/MockMakerDocSpec.groovy
- spock-specs/src/test/groovy/org/spockframework/mock/runtime/ByteBuddyMockFactoryConcurrentSpec.groovy
- spock-specs/src/test/groovy/org/spockframework/mock/runtime/ByteBuddyMockMakerSpec.groovy
- spock-specs/src/test/groovy/org/spockframework/mock/runtime/MockMakerRegistrySpec.groovy
- spock-specs/src/test/groovy/org/spockframework/mock/runtime/mockito/AccessProtectedJavaBaseClass.java
- spock-specs/src/test/groovy/org/spockframework/mock/runtime/mockito/MockitoMockMakerSpec.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/mock/JavaSpies.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/mock/JavaStubs.groovy
The MockitoMockMaker provides the ability to mock
final classes and final methods with the InlineMockMaker of Mockito.
The MockitoMockMaker would fix #735 and #683.
> MockitoInlineMockMaker provides mocking on final classes and methods

- spock-core/src/main/java/org/spockframework/runtime/FeatureNode.java
- spock-core/src/main/java/org/spockframework/runtime/PlatformSpecRunner.java
- spock-core/src/main/java/org/spockframework/runtime/SpecNode.java
- spock-specs/src/test/groovy/org/spockframework/runtime/RunListenerSpec.groovy
> Properly call specSkipped and featureSkipped

- docs/extensions.adoc
- docs/interaction_based_testing.adoc
- spock-specs/src/test/groovy/org/spockframework/docs/interaction/StaticSpyDocSpec.groovy
Moved static mocking into own section.
Added sample to do stubbing of all static methods.
> Static mocking documentation updates

- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/RetryIterationInterceptor.java
- spock-specs/src/test/groovy/org/spockframework/smoke/extension/RetryFeatureExtensionSpec.groovy
> Make RetryExtension more parallel-safe (#1700)

- spock-core/src/main/java/org/spockframework/compiler/ConditionRewriter.java
- spock-core/src/main/java/org/spockframework/runtime/SpockRuntime.java
- spock-specs/src/test/groovy/org/spockframework/smoke/condition/CollectionConditionRendering.groovy
- spock-specs/src/test/resources/snapshots/org/spockframework/smoke/ast/condition/CollectionConditionAstSpec/regex_find_conditions_are_transformed_correctly.groovy
- spock-specs/src/test/resources/snapshots/org/spockframework/smoke/ast/condition/CollectionConditionAstSpec/regex_match_conditions_are_transformed_correctly.groovy
The rendering is not as fancy as the top-level usages, but at least they should work in any depth now.
> Support collection matchers nested in complex assertions

- spock-core/src/main/java/org/spockframework/runtime/SpockRuntime.java
- spock-specs/src/test/groovy/org/spockframework/smoke/condition/CollectionConditionRendering.groovy
> Fix nested regex finding in conditions (#1930)

- docs/release_notes.adoc
- spock-core/src/main/java/org/spockframework/runtime/ExtensionClassesLoader.java
- spock-core/src/main/java/org/spockframework/util/ReflectionUtil.java
- spock-specs/src/test/groovy/org/spockframework/util/ReflectionUtilSpec.groovy
ReflectionUtil now also uses the ContextClassLoader to load classes, which enables env like OSGi to resolve classes.
> Support ContextClassLoader when loading optional classes

- spock-core/src/main/java/org/spockframework/compiler/WhereBlockRewriter.java
- spock-specs/src/test/groovy/org/spockframework/smoke/ast/DataTablesAstSpec.groovy
- spock-specs/src/test/resources/snapshots/org/spockframework/smoke/ast/DataTablesAstSpec/using_a_variable_in_a_cell_multiple_times_compiles.groovy
> Fix using the same previous data table column multiple times in the same cell (#2083)

- spock-core/src/main/java/org/spockframework/util/RenderUtil.java
- spock-specs/src/test/groovy/org/spockframework/smoke/condition/ArrayComparisonRendering.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/condition/ValueRendering.groovy
- spock-specs/src/test/groovy/org/spockframework/smoke/mock/TooFewInvocations.groovy
Update `RenderUtils` to provide a user-friendly visualization of multidimensional arrays. The implementations recursively unwraps arrays until it discovers an array that can be rendered using default Groovy methods.
> Render multidimensional arrays in comparisons and invocation matchers

- docs/release_notes.adoc
- spock-core/src/main/java/org/spockframework/runtime/extension/builtin/RestoreSystemPropertiesExtension.java
- spock-specs/src/test/groovy/org/spockframework/smoke/extension/RestoreSystemPropertiesExtension.groovy
> Fix `@RestoreSystemProperties` for iterations

- docs/release_notes.adoc
- spock-core/src/main/java/org/spockframework/compiler/SpecRewriter.java
- spock-core/src/main/java/org/spockframework/util/ReflectionUtil.java
- spock-specs/src/test/groovy/org/spockframework/smoke/issues/StackFrameReproducer.groovy
- spock-specs/src/test/groovy/org/spockframework/util/ReflectionUtilSpec.groovy
- **Fix #2080 `VerifyError`**
- **Release notes**
> Fix `VerifyError: Stack map does not match...`

- build-logic/asciidoc-extensions/src/main/java/org/spockframework/plugins/asciidoctor/IncludedSourceLinker.java
The recognition was already there and since AsciidoctorJ 2.5.12 also working
> Update comment about literal block recognition

- docs/spock_primer.adoc
- docs/utilities.adoc
> Clarify collection conditions in docs
